/**
 * For the full copyright and license information, please view the
 * docs/licenses/LICENSE.txt file that was distributed with this source code.
 */

/**
 * Central selector map of the extra property definition form page (components-map.ts style):
 * every DOM hook of the row builders lives here — the data-role/data-tpl attributes and CSS
 * classes rendered by FormTheme/definition_form_theme.html.twig, and the ids of the
 * field-definition card inputs some builders react to. Components never hard-code a selector.
 */
export default {
  catalogsPayload: '[data-role="extra-property-catalogs"]',
  constraintCatalogPayload: '[data-role="extra-property-constraint-catalog"]',
  placementList: '[data-role="placement-list"]',
  constraintBuilder: '[data-role="constraint-builder"]',
  developerFields: '[data-role="developer-fields"]',
  // Field-definition card inputs observed by the builders (scope drives the per-language zone,
  // type drives the default form type placeholder).
  fieldTypeSelect: '#extra_property_definition_field_definition_type',
  scopeSelect: '#extra_property_definition_field_definition_scope',
  /** One of the inert markup templates rendered by the form theme, cloned via cloneTemplate(). */
  template: (name: string): string => `template[data-tpl="${name}"]`,
  /** A row field input, matched by its Symfony field name suffix ("...[grid_id]"). */
  rowField: (field: string): string => `[name$="[${field}]"]`,
  subsection: {
    rows: '[data-role="rows"]',
    row: '[data-role="row"]',
    builderView: '[data-role="builder-view"]',
    countBadge: '[data-role="count-badge"]',
    emptyState: '[data-role="empty-state"]',
    addRow: '[data-role="add-row"]',
    removeRow: '[data-role="remove-row"]',
    structuredFields: '[data-role="structured-fields"]',
    unknownPill: '[data-role="unknown-pill"]',
  },
  constraint: {
    perLanguageZone: '[data-role="per-language-zone"]',
    langRows: '[data-role="lang-rows"]',
    addLangRow: '[data-role="add-lang-row"]',
    optionsDisplay: '[data-role="options-display"]',
    optionsEditor: '[data-role="options-editor"]',
    optionField: '.extra-property-options-editor__field',
    optionLabel: '.extra-property-options-editor__label',
    optionInput: '.extra-property-options-editor__input',
    optionRemove: '.extra-property-options-editor__remove',
    inactiveZoneClass: 'extra-property-lang-zone--inactive',
  },
  // Shared dropdown chrome (suggestion dropdowns + the form field anchor tree).
  dropdown: {
    wrapClass: 'extra-property-anchor-wrap',
    wrap: '.extra-property-anchor-wrap',
    anchorWrap: '[data-role="anchor-wrap"]',
    headingClass: 'extra-property-anchor-heading',
    option: '.extra-property-anchor-option',
    visibleOption: '.extra-property-anchor-option:not(.d-none)',
    optionLabel: '.extra-property-anchor-option__label',
    optionDetail: '.extra-property-anchor-option__path',
    customOptionClass: 'extra-property-anchor-option--custom',
    groupOptionClass: 'extra-property-anchor-option--group',
    /** Tree indentation classes generated by SCSS (see the matching @for loop). */
    depthClass: (depth: number): string => `extra-property-anchor-option--depth-${depth}`,
  },
  api: {
    methodChips: '[data-role="method-chips"]',
    allMethodsChip: '[data-role="all-methods"]',
    endpointSearch: '[data-role="endpoint-search"]',
    endpointSearchWrapper: '[data-role="endpoint-search-wrapper"]',
  },
  developer: {
    formTypeInput: 'input[name$="[form_type]"]',
    formOptionsTextarea: 'textarea[name$="[form_options]"]',
    jsonStatus: '[data-role="json-status"]',
    formatJson: '[data-role="format-json"]',
    jsonStatusClass: 'extra-property-json-status',
  },
};
