<?php
/**
 * For the full copyright and license information, please view the
 * docs/licenses/LICENSE.txt file that was distributed with this source code.
 */
declare(strict_types=1);

namespace PrestaShop\PrestaShop\Adapter\Container;

use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * This interface is only used when we build containers for legacy environment. It
 * is common to LegacyContainer and LegacyContainerBuilder.
 *
 * It allows to easily (and without losing performance) detect if the container is a
 * Symfony one (generated by kernel) or a legacy one (generated by PrestaShop core).
 */
interface LegacyContainerInterface extends ContainerInterface
{
}
