<?php $this->displayTemplate('header') ?>

<?php if (Tools::getMemoryLimit() < Tools::getOctets('32M')): ?>
	<div class="warnBlock"><?php echo $this->l('PrestaShop requires at least 32M of memory to run, please check the memory_limit directive in php.ini or contact your host provider'); ?></div>
<?php endif; ?>

<?php if ($this->can_upgrade): ?>
	<div class="warnBlock">
		<img src="theme/img/pict_error.png" alt="" style="vertical-align: middle;" /> &nbsp;
		<?php echo $this->l(
			'<b>Warning: You cannot use anymore this tool to upgrade your store.</b><br /><br />You already have <b>PrestaShop version %1$s installed</b>.<br /><br />If you want to upgrade to the latest version please read our documentation: <a href="%2$s">%2$s</a>',
			$this->ps_version, $this->getDocumentationUpgradeLink()
		) ?></div>
<?php endif; ?>

<h2><?php echo $this->l('Welcome to the PrestaShop %s Installer.', _PS_INSTALL_VERSION_) ?></h2>
<p><?php echo $this->l('The installation of PrestaShop is quick and easy. In just a few moments, you will become part of a community consisting of more than 130,000 merchants. You are on the way to creating your own unique online store that you can manage easily every day.') ?></p>
<p><?php echo $this->l('If you need help, do not hesitate to check <a href="%1$s" target="_blank">our documentation</a> or to contact our support team: %2$s', $this->getDocumentationLink(), $this->getPhone()) ?></p>

<!-- List of languages -->
<?php if (count($this->language->getIsoList()) > 1): ?>
	<h2><?php echo $this->l('Continue the installation in:') ?></h2>
	<ul id="langList" style="line-height: 20px;">
	<?php foreach ($this->language->getIsoList() as $iso): ?>
		<li>
			<label>
				<input type="radio" value="<?php echo $iso ?>" <?php echo ($iso == $this->language->getLanguageIso()) ? 'checked="checked"' : '' ?> name="language" style="vertical-align: middle; margin-right: 0;" />
				<?php if (file_exists(_PS_INSTALL_LANGS_PATH_.$iso.'/flag.jpg')): ?>
					<img src="langs/<?php echo $iso ?>/flag.jpg" alt="<?php echo $iso ?>" style="vertical-align: middle;" />
				<?php else: ?>
					<img src="theme/img/noflag.jpg" alt="<?php echo $iso ?>" style="vertical-align: middle;" />
				<?php endif; ?>
				<?php echo $this->language->getLanguage($iso)->getMetaInformation('name') ?>
			</label>
		</li>
	<?php endforeach; ?>
	</ul>
<?php endif; ?>

<p><?php echo $this->l('The language selection above only applies to the Installation Assistant. Once your store is installed, you can choose the language of your store from over %d translations, all for free!', 55); ?> </p>

<?php $this->displayTemplate('footer') ?>