<?php
/**
 * For the full copyright and license information, please view the
 * docs/licenses/LICENSE.txt file that was distributed with this source code.
 */

namespace PrestaShop\PrestaShop\Core\Image\Parser;

/**
 * Class ImageTagPathParser parses "src" attribute of given image tag and prefixed it with shop's uri.
 *
 * This service helps retrieving image path from image tag generated by legacy ImageManager::thumbnail() method
 * so image can be displayed in new pages.
 */
final class ImageTagSourceParser implements ImageTagSourceParserInterface
{
    /**
     * {@inheritdoc}
     */
    public function parse(string $imageTag): ?string
    {
        $replacement = 'src="/';
        $imageTag = preg_replace('/src="(\.\.\/|\.\/)+/', $replacement, $imageTag);

        if (null === $imageTag) {
            return null;
        }

        preg_match('/src="\/([^"]+)"/', $imageTag, $path);

        if (empty($path[1])) {
            return null;
        }

        return sprintf('/%s', $path[1]);
    }
}
