module.exports = {
  Location: {
    State: {
      country_select: '//*[@id="table-state"]//select[@name="stateFilter_cl!id_country"]',
      search_button: '//*[@id="submitFilterButtonstate"]',
      state_field_column: '//*[@id="table-state"]//tr[%L]//td[%C]',
      search_country_option_list: '//*[@id="table-state"]//select[@name="stateFilter_cl!id_country"]/option[text()="%B"]'
    },
    Zone: {
      add_new_zone_button: '//*[@id="page-header-desc-zone-new_zone"]',
      cancel_button: '//*[@id="zone_form_cancel_btn"]',
      zones_table: '//*[@id="table-zone"]',
      name_input: '//*[@id="name"]',
      save_button: '//*[@id="zone_form_submit_btn"]',
      reset_button: '//*[@id="table-zone"]//button[@name="submitResetzone"]',
      alert_panel: '//*[@id="content"]/div[@class="bootstrap"]/div[contains(@class, "%I")]',
      search_zone_input: '//*[@id="table-zone"]//input[@name="zoneFilter_name"]',
      search_id_input: '//*[@id="table-zone"]//input[@name="zoneFilter_id_zone"]',
      search_button: '//*[@id="submitFilterButtonzone"]',
      enabled_disabled_icon: '//*[@id="table-zone"]//tr[%ID]/td[4]/a/i[@class="%ICON"]',
      sort_icon: '//*[@id="table-zone"]//span[contains(text(),"%B")]/a[%W]',
      number_zone_span: '//*[@id="form-zone"]//span[@class="badge"]',
      element_zone_table: '//*[@id="table-zone"]//tbody/tr[%ID]/td[%B]',
      search_enabled_list: '//*[@id="table-zone"]//select[@name="zoneFilter_active"]',
      edit_delete_button: '//*[@id="table-zone"]//td[5]//a[@title="%B"]',
      dropdown_button: '//*[@id="table-zone"]//td[5]//button',
      bulk_action_button: '//*[@id="bulk_action_menu_zone"]',
      action_group_button: '(//*[@id="form-zone"]//div[contains(@class, "bulk-actions")]//a)[%ID]',
      checkbox_input: '#table-zone > tbody > tr:nth-child(%B) > td.row-selector.text-center > input',
      search_by_zone_checkbox: '//*[@id="table-zone"]//tbody//td[contains(text(),"%B")]/../td[1]',
      search_by_zone_icon: '//*[@id="table-zone"]//tbody//td[contains(text(),"%B")]/../td[4]/a/i[@class="%ICON"]'
    },
    Country: {
      search_zone_list: '//*[@id="table-country"]//select[@name="countryFilter_z!id_zone"]',
      reset_button: '//*[@id="table-country"]//button[@name="submitResetcountry"]',
      search_zone_option_list: '//*[@id="table-country"]//select[@name="countryFilter_z!id_zone"]/option[text()="Asiaaa"]',
      add_new_country_button: '//*[@id="page-header-desc-country-new_country"]',
      country_input: '//*[@id="name_1"]',
      iso_code_input: '//*[@id="iso_code"]',
      call_prefix_input: '//*[@id="call_prefix"]',
      default_currency_select: '//*[@id="id_currency"]',
      zone_select: '//*[@id="id_zone"]',
      need_zip_code_yes_label: '//label[@for="need_zip_code_on"]',
      zip_code_format_input: '//*[@id="zip_code_format"]',
      clear_format_button: '//*[@id="eraseCurrentLayout"]',
      address_format_field_textarea: '//*[@id="ordered_fields"]',
      address_format_tab: '//*[@id="custom-address-fields"]//a[contains(text(),"%B")]',
      customer_birthday_button: '//*[@id="Customer:birthday"]',
      customer_lastname_button: '//*[@id="Customer:lastname"]',
      customer_firstname_button: '//*[@id="Customer:firstname"]',
      address_last_name_button: '//*[@id="lastname"]',
      address_first_name_button: '//*[@id="firstname"]',
      address_address1_button: '//*[@id="address1"]',
      address_address2_button: '//*[@id="address2"]',
      address_dni_button: '//*[@id="dni"]',
      address_postcode_button: '//*[@id="postcode"]',
      address_city_button: '//*[@id="city"]',
      address_phone_button: '//*[@id="phone"]',
      country_name_button: '//*[@id="Country:name"]',
      save_button: '//*[@id="country_form_submit_btn"]',
      alert_panel: '//*[@id="content"]/div[@class="bootstrap"]/div[contains(@class, "%B")]',
      search_iso_code_input: '//*[@id="table-country"]//input[@name="countryFilter_iso_code"]',
      search_country_input: '//*[@id="table-country"]//input[@name="countryFilter_b!name"]',
      search_id_input: '//*[@id="table-country"]//input[@name="countryFilter_id_country"]',
      search_button: '//*[@id="submitFilterButtoncountry"]',
      number_country_span: '//*[@id="form-country"]//span[@class="badge"]',
      element_country_table: '//*[@id="table-country"]//tr[%ID]/td[%B]',
      enabled_disabled_icon: '//*[@id="table-country"]//tr[%ID]/td[7]/a/i[@class="%ICON"]',
      search_enabled_list: '//*[@id="table-country"]//select[@name="countryFilter_a!active"]',
      sort_icon: '//*[@id="table-country"]//span[contains(text(),"%B")]/a[%W]',
      pagination_button: '//*[@id="form-country"]//div[contains(@class,"pagination")]//button',
      pagination_element: '//*[@id="form-country"]//div[contains(@class,"pagination")]//li/a[contains(text(),"%NUMBER")]',
      edit_button: '//*[@id="table-country"]//tbody/tr[1]/td[8]//a',
      use_default_format_button: '//*[@id="useDefaultLayoutSystem"]',
      use_last_registered_format_button: '//*[@id="useLastDefaultLayout"]',
      contain_states_yes_button: '//label[@for="contains_states_on"]',
      restrict_country_selections_button: '//*[@id="conf_id_PS_RESTRICT_DELIVERED_COUNTRIES"]//label[@for="PS_RESTRICT_DELIVERED_COUNTRIES_%B"]',
      country_option_save_button: '//*[@id="country_fieldset_general"]//button',
      bulk_action_button: '//*[@id="form-country"]//button[contains(@class,"dropdown-toggle")]',
      action_group_button: '(//*[@id="form-country"]//div[contains(@class, "bulk-actions")]//a)[%ID]'
    }
  }
};
