# todo uncomment all legacy links when page is finished.
admin_countries_index:
  path: /
  methods: GET
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\Improve\International\CountryController::indexAction'
    _legacy_controller: AdminCountries
    _legacy_link: AdminCountries
    _legacy_feature_flag: country

admin_countries_search:
  path: /
  methods: POST
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\CommonController::searchGridAction
    gridDefinitionFactoryServiceId: prestashop.core.grid.definition.factory.country
    redirectRoute: admin_countries_index
    _legacy_controller: AdminCountries
    _legacy_link: AdminCountries:submitFiltercountry
    _legacy_feature_flag: country

admin_countries_create:
  path: /new
  methods: [ GET, POST ]
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\Improve\International\CountryController::createAction'
    _legacy_controller: AdminCountries
    _legacy_link: AdminCountries:addCountry
    _legacy_feature_flag: country

admin_countries_edit:
  path: /{countryId}/edit
  methods: [ GET, POST ]
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\Improve\International\CountryController::editAction'
    _legacy_controller: AdminCountries
    _legacy_link: AdminCountries:updateCountry
    _legacy_feature_flag: country
    _legacy_parameters:
      id_country: countryId
  requirements:
    countryId: \d+

admin_countries_delete:
  path: /{countryId}/delete
  methods: [ POST, DELETE ]
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\Improve\International\CountryController::deleteAction'
    _legacy_controller: AdminCountries
    _legacy_link: AdminCountries:deleteCountry
    _legacy_feature_flag: country
    _legacy_parameters:
      id_country: countryId
  requirements:
    countryId: \d+

admin_countries_save_options:
  path: /options
  methods: [ POST ]
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\Improve\International\CountryController::saveOptionsAction'
    _legacy_controller: AdminCountries
    _legacy_link: AdminCountries:submitOptionscountry
    _legacy_feature_flag: country

admin_countries_bulk_enable_status:
  path: /bulk-status-enable
  methods: [ POST ]
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\Improve\International\CountryController::bulkEnableAction'
    _legacy_controller: AdminCountries
    _legacy_link: AdminCountries:submitBulkenableSelectioncountry
    _legacy_feature_flag: country

admin_countries_bulk_disable_status:
  path: /bulk-status-disable
  methods: [ POST ]
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\Improve\International\CountryController::bulkDisableAction'
    _legacy_controller: AdminCountries
    _legacy_link: AdminCountries:submitBulkdisableSelectioncountry
    _legacy_feature_flag: country

admin_countries_bulk_update_zone:
  path: /bulk-update-zone
  methods: [ POST ]
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\Improve\International\CountryController::bulkUpdateZoneAction'
    _legacy_controller: AdminCountries
    _legacy_link: AdminCountries:submitBulkAffectZonecountry
    _legacy_feature_flag: country

admin_countries_toggle_status:
  path: /{countryId}/toggle-status
  methods: [ POST ]
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\Improve\International\CountryController::toggleStatusAction'
    _legacy_controller: AdminCountries
    _legacy_link: AdminCountries:statuscountry
    _legacy_feature_flag: country
    _legacy_parameters:
      id_country: countryId
  requirements:
    countryId: \d+
