admin_email_body_translation_index:
  path: /{locale}
  methods: [ GET ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Improve\International\EmailBodyTranslationController::indexAction
    _legacy_controller: AdminTranslations
    _legacy_feature_flag: email_body_translation

admin_email_body_translation_search:
  path: /{locale}/search
  methods: [ POST ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Improve\International\EmailBodyTranslationController::searchAction
    _legacy_controller: AdminTranslations
    _legacy_feature_flag: email_body_translation

admin_email_body_translation_edit:
  path: /{locale}/{source}/{templateName}/edit
  methods: [ GET, POST ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Improve\International\EmailBodyTranslationController::editAction
    _legacy_controller: AdminTranslations
    _legacy_feature_flag: email_body_translation
