module.exports = {
  Customer: {
    customer_menu: '#subtab-AdminParentCustomer"] a',
    customers_subtab: '#subtab-AdminCustomers"] a',
    new_customer_button: '#page-header-desc-customer-new_customer , #page-header-desc-configuration-add',
    social_title_button: '#customer_gender_id_1',
    first_name_input: '#customer_first_name',
    last_name_input: '#customer_last_name',
    email_address_input: '#customer_email',
    password_input: '#customer_password',
    days_select: '#customer_birthday_day',
    month_select: '#customer_birthday_month',
    years_select: '#customer_birthday_year',
    save_button: '.card-footer button',
    customer_filter_by_email_input: '#customer_email',
    email_address_value: '#customer_grid_table tbody td:nth-of-type(%ID)',
    reset_button: '#customer_grid_table button[name="submitResetcustomer"]',
    edit_button: '#customer_grid_table a[data-original-title="Edit"]',
    dropdown_toggle: '#customer_grid_table [data-toggle="dropdown"]',
    delete_button: '#customer_grid_table a[class*="delete-customer"]',
    delete_first_option: '#delete_customers_delete_method_0',
    delete_second_option: '#delete_customers_delete_method_1',
    delete_confirmation_button: '#content input[value="Delete"]',
    select_customer: '#customer_grid_table tbody .md-checkbox',
    bulk_actions_button: '#customer_grid button[data-toggle="dropdown"]',
    bulk_actions_delete_button: '#customer_grid_bulk_action_delete_selection',
    empty_list_icon: '#customer_grid_table div.list-empty-msg',
    empty_list_text: '#customer_grid_table tbody tr td p:last-of-type',
    customer_link: '#customer_grid_table td[contains(text(),"%ID")]',
    Partner_offers: 'form label[for="customer_is_partner_offers_subscribed_1"]',
    first_name_value: '#customer_grid_table tr:nth-of-type(%ID) > td:nth-of-type(4)',
    last_name_value: '#customer_grid_table tr:nth-of-type(%ID) > td:nth-of-type(5)',
    view_button: '#customer_grid_table a[title=View]',
    valid_orders: '#container-customer div:nth-child(1) > span.label-success',
    total_amount: '#container-customer  div:nth-child(2)  div.panel div.col-lg-6:nth-child(1)',
  }
};
