module.exports = {
  Customer: {
    customer_menu: '#subtab-AdminParentCustomer"] a',
    customers_subtab: '#subtab-AdminCustomers"] a',
    new_customer_button: '#page-header-desc-customer-new_customer , #page-header-desc-configuration-add',
    social_title_button: '#customer_gender_id_1',
    first_name_input: '#customer_first_name',
    last_name_input: '#customer_last_name',
    email_address_input: '#customer_email',
    password_input: '#customer_password',
    days_select: '#customer_birthday_day',
    month_select: '#customer_birthday_month',
    years_select: '#customer_birthday_year',
    save_button: '.card-footer button',
    customer_filter_by_email_input: '#form-customer input[name="customerFilter_email"]',
    email_address_value: '#form-customer td:nth-of-type(%ID)',
    reset_button: '#table-customer button[name="submitResetcustomer"]',
    edit_button: '#form-customer a[title="Edit"]',
    dropdown_toggle: '#form-customer button[data-toggle="dropdown"]',
    delete_button: '#form-customer a[title="Delete"]',
    delete_first_option: '#deleteMode_real ',
    delete_second_option: '#deleteMode_deleted ',
    delete_confirmation_button: '#content input[value="Delete"]',
    select_customer: '#form-customer input[name="customerBox"]',
    bulk_actions_button: '#bulk_action_menu_customer ',
    bulk_actions_delete_button: '#form-customer div.bulk-actions a[onclick*="submitBulkdeletecustomer"]',
    empty_list_icon: '#table-customer div.list-empty-msg',
    customer_link: '#table-address td[contains(text(),"%ID")]',
    Partner_offers: 'form label[for="customer_is_partner_offers_subscribed_1"]',
    first_name_value: '#table-customer tr:nth-of-type(%ID) > td:nth-of-type(4)',
    last_name_value: '#table-customer tr:nth-of-type(%ID) > td:nth-of-type(5)',
    view_button: '#form-customer a[title=View]',
    valid_orders: '#container-customer div:nth-child(1) > span.label-success',
    total_amount: '#container-customer  div:nth-child(2)  div.panel div.col-lg-6:nth-child(1)',
  }
};
