scheb_two_factor:
  security_tokens:
    - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken

  totp:
    enabled: true
    issuer: 'PrestaShop'
    template: '@PrestaShop/Admin/TwoFactorAuthentication/2fa_form.html.twig'

  email:
    enabled: true
    mailer: 'PrestaShop\PrestaShop\Adapter\TotMailer\TwoFactorAuthCodePrestashopMailer'
    template: '@PrestaShop/Admin/TwoFactorAuthentication/2fa_form.html.twig'

  trusted_device:
    enabled: true
    cookie_name: trusted_device

services:
  PrestaShopBundle\SchebTwoFactor\DynamicIssuerTotpFactory:
    decorates: 'scheb_two_factor.security.totp_factory'
    arguments:
      $server: '%scheb_two_factor.totp.server_name%'
      $issuer: '%scheb_two_factor.totp.issuer%'
      $customParameters: '%scheb_two_factor.totp.parameters%'
      $configuration: '@PrestaShop\PrestaShop\Adapter\Configuration'
