<?php
/**
 * For the full copyright and license information, please view the
 * docs/licenses/LICENSE.txt file that was distributed with this source code.
 */

namespace PrestaShopBundle\Entity\Repository;

/**
 * ShopRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return bool true if multiple shops exists
     */
    public function haveMultipleShops()
    {
        return count($this->findAll()) > 1;
    }

    /**
     * Get a list of shops for a given search term
     *
     * @param string $searchTerm
     *
     * @return array
     */
    public function findBySearchTerm(string $searchTerm): array
    {
        $qb = $this->createQueryBuilder('s')
            ->select(['s', 'sg'])
            ->join('s.shopGroup', 'sg')
            ->where('s.active = true')
            ->andWhere('s.deleted = false')
            ->andWhere('LOWER(s.name) LIKE :searchTerm')
            ->setParameter('searchTerm', '%' . strtolower($searchTerm) . '%');

        return $qb->getQuery()->getResult();
    }
}
