module.exports = {
  AddProductPage: {
    exit_welcome_button: '.btn btn-tertiary-outline .btn-lg .onboarding-button-shut-down',
    click_outside: '#product_catalog_list div:nth-child(2) div table thead tr:nth-child(1) th:nth-child(3)',
    logout: '#header_logout',
    products_subtab: '#subtab-AdminCatalog',
    go_to_catalog_button: '#form > div.product-footer.justify-content-md-center > div.col-sm-5.col-lg-7.text-right > div.btn-group.hide.dropdown.show > div > a.dropdown-item.go-catalog.js-btn-save',
    new_product_dropdown_button: '#form > div.product-footer.justify-content-md-center > div.col-sm-5.col-lg-7.text-right > div.btn-group.hide.dropdown.show > div > a.dropdown-item.new-product.js-btn-save',
    more_option_button: '.btn.btn-primary.dropdown-toggle',
    basic_settings_tab: '#tab_step1 a',
    new_product_button: '#page-header-desc-configuration-add',
    product_name_input: '#form_step1_name_1',
    product_name_fr_input: '#form_step1_name_2',
    save_product_button: '#form > div[class*=product-footer] button[type=submit]',
    green_validation_notice: '[class="growl growl-notice growl-medium"]',
    close_validation_button: '.growl-close',
    validation_msg: '#growls-default > .growl-notice > .growl-message:not(:empty)',
    red_validation_notice: '[class="growl growl-error growl-medium"]',
    description_tab: '[href="#description"]',
    quantity_shortcut_input: '#form_step1_qty_0_shortcut',
    picture: '[class="dz-hidden-input"]',
    picture_cover: '.iscover',
    product_online_toggle: '.switch-input ',
    catalogue_filter_by_name_input: 'input[name=filter_column_name]',
    catalogue_submit_filter_button: 'button[name=products_filter_submit]',
    variations_type_button: '#show_variations_selector > div:nth-of-type(2) > label > input',
    variations_tab: '#tab_step3 > a',
    variations_input: '#form_step3_attributes-tokenfield ',
    variations_generate: '#create-combinations',
    variations_select: '#attributes-generator div:nth-child(2) div:nth-child(1) fieldset div span div div div',
    var_selected: '#toggle-all-combinations',
    var_selected_quantitie: '#product_combination_bulk_quantity',
    combinations_thead: '#combinations_thead > tr > th:nth-of-type(7)',
    save_quantitie_button: '#apply-on-combinations',
    add_feature_to_product_button: '#add_feature_button ',
    feature_select: '#features-content div div:nth-child(%NUMBER) div:nth-child(1) fieldset span span:nth-child(1) span',
    select_feature_created: 'html body span span:nth-child(1) input.select2-search__field',
    feature_select_button: '#select2-form_step1_features_%ID_feature-container',
    feature_select_button1: '#features-content div div div:nth-child(1) fieldset span span:nth-child(1) span',
    customized_value_input: '#form_step1_features_%ID_custom_value_1 ',
    feature_btn: '#add_feature_button ',
    result_feature_select: '#select2-form_step1_features_%ID_feature-results li',
    summary_textarea: '#form_step1_description_short .mce-edit-area',
    summary_input: 'textarea#form_step1_description_short_1',
    description_textarea: '#form_step1_description',
    description_input: '#form_step1_description_1',
    tab_description: '#tab_description > a',
    feature_value_select: '#form_step1_features_%ID_value:%V',
    product_create_category_btn: '#add-category-button',
    product_type: '#form_step1_type_product',
    product_category_name_input: '#form_step1_new_category_name',
    category_create_btn: '#add-categories #form_step1_new_category_save',
    category_home: '#form_step1_categories ul li div label input',
    product_add_brand_btn: '#add_brand_button',
    product_brand_select: '#manufacturer-content span.select2-selection--single.select2-selection',
    product_brand_select_option: '#select2-form_step1_id_manufacturer-results > li:nth-child(2)',
    search_product_pack: '#form_step1_inputPackItems',
    product_item_pack: '#js_form_step1_inputPackItems .tt-dataset .tt-suggestion.tt-selectable:nth-child(1)',
    product_pack_item_quantity: '#form_step1_inputPackItems-curPackItemQty',
    product_pack_add_button: '#form_step1_inputPackItems-curPackItemAdd',
    add_related_product_btn: '#add-related-product-button',
    search_add_related_product_input: '#form_step1_related_products',
    related_product_item: '#related-product #related-content .search.search-with-icon .tt-menu.tt-open .tt-dataset.tt-dataset-3',
    product_add_feature_btn: '#add_feature_button',
    feature_select_option: '#select2-form_step1_features_0_feature-results > li:nth-child(2)',
    feature_custom_value_height: '#form_step1_features_0_custom_value_1',
    feature_select_option_text: '#select2-form_step1_features_%ID_feature-results li[text()="%V"]',
    feature_custom_value: '#form_step1_features_%ID_custom_value_1 ',
    priceTE_shortcut: '#form_step1_price_shortcut',
    priceTTC_shortcut: '#form_step1_price_ttc_shortcut',
    product_reference: '#form_step6_reference',
    product_quantities_tab: '#tab_step3 > a',
    product_quantity_input: '#form_step3_qty_0',
    minimum_quantity_sale: '#form_step3_minimal_quantity',
    pack_stock_type: '#form_step3_pack_stock_type',
    virtual_associated_file: '#form_step3_virtual_product_is_virtual_file_%ID',
    virtual_select_file: '#form_step3_virtual_product_file',
    virtual_file_name: '#form_step3_virtual_product_name',
    virtual_file_number_download: '#form_step3_virtual_product_nb_downloadable',
    virtual_expiration_file_date: '#form_step3_virtual_product_expiration_date',
    virtual_number_days: '#form_step3_virtual_product_nb_days',
    virtual_save_attached_file: '#form_step3_virtual_product_save',
    pack_availability_preferences: '#form_step3_out_of_stock_0',
    pack_label_in_stock: '#form_step3_available_now_1',
    pack_label_out_stock: '#form_step3_available_later_1',
    pack_availability_date: '#form_step3_available_date',
    pack_unit_price: '#form_step2_unit_price ',
    product_shipping_tab: '#tab_step4 > a',
    shipping_width: '#form_step4_width',
    shipping_height: '#form_step4_height',
    shipping_depth: '#form_step4_depth',
    shipping_weight: '#form_step4_weight',
    shipping_width_unit: '#form_step4_width .. span',
    shipping_height_unit: '#form_step4_height .. span',
    shipping_depth_unit: '#form_step4_depth .. span',
    shipping_weight_unit: '#form_step4_weight .. span',
    shipping_fees: '#form_step4_additional_shipping_cost',
    shipping_available_carriers: '#form_step4_selectedCarriers_1',
    product_combinations_tab: '#tab_step3 a',
    product_combinations: '#show_variations_selector div:nth-child(%I) label input',
    combination_size_s: '#attribute-group-1 label[for="attribute-1"]',
    combination_size_m: '#attribute-group-1 label[for=attribute-2]',
    combination_color: '#attribute-group-2 label[for="attribute-%ID"]',
    combination_dimension: '#attribute-group-3 label[for="attribute-%ID"]',
    combination_color_beige: '#attribute-group-2 label[for=attribute-7]',
    combination_total_number: '#js-bulk-combinations-total ',
    combination_color_green: ' label[for="attribute-15"]',
    combination_color_red: ' label[for="attribute-10"]',
    combination_generate_button: '#create-combinations ',
    combination_impact_price_input: '#attribute_%NUMBER td.attribute-price input',
    combination_final_price_span: '#attribute_%NUMBER td.attribute-finalprice span',
    combination_availability_preferences: '#form_step3_out_of_stock_%NUMBER',
    combination_label_in_stock: '#form_step3_available_now_1 ',
    combination_label_out_stock: '#form_step3_available_later_1 ',
    combination_panel: '#accordion_combinations > tr:nth-of-type(%NUMBER)',
    combination_quantity: '#combination_%NUMBER_attribute_quantity ',
    combination_available_date: '#combination_%NUMBER_available_date_attribute ',
    combination_min_quantity: '#combination_%NUMBER_attribute_minimal_quantity ',
    combination_reference: '#combination_%NUMBER_attribute_reference ',
    combination_whole_sale: '#combination_%NUMBER_attribute_wholesale_price ',
    combination_low_stock: '#combination_%NUMBER_attribute_low_stock_threshold ',
    combination_priceTI: '#combination_%NUMBER_attribute_priceTI ',
    combination_attribute_unity: '#combination_%NUMBER_attribute_unity ',
    combination_attribute_weight: '#combination_%NUMBER_attribute_weight ',
    combination_attribute_isbn: '#combination_%NUMBER_attribute_isbn ',
    combination_attribute_ean13: '#combination_%NUMBER_attribute_ean13 ',
    combination_attribute_upc: '#combination_%NUMBER_attribute_upc ',
    combination_attribute_image: '#attribute_%NUMBER td:nth-child(2) img',
    combination_attribute_quantity: '#attribute_%NUMBER td:nth-child(6) div input',
    combination_image: '#combination_%NUMBER_id_image_attr div:nth-child(2) img',
    combination_edit: '#attribute_%NUMBER td:nth-child(7) div:nth-child(1) a',
    combination_default_button: ' input.attribute-default [data-id="%NUMBER"]',
    default_combination: '#combination_%NUMBER_attribute_default ',
    back_to_product: '#combination_form_%NUMBER div:nth-child(2) div:nth-child(1) button',
    product_pricing_tab: '#tab_step2 > a',
    unit_price: '#form_step2_unit_price',
    unity: '#form_step2_unity',
    pricing_tax_rule_select: '#step2 div div div div div:nth-child(3) div div:nth-child(1) span',
    pricing_tax_rule_input: ' span.select2-search input[type="search"]',
    pricing_tax_rule_option: '#select2-form_step2_id_tax_rules_group-results li[contains(text(), "%T")]',
    pricing_wholesale: '#form_step2_wholesale_price',
    pricing_tax_rule_arrow_button: '#step1 div:nth-child(3) span.select2-selection__arrow b[role="presentation"]',
    tax_rule_value: ' span.select2-results ul li[contains(text(), "%ID")]',
    pricing_add_specific_price_button: '#specific-price a',
    specific_price_starting_at_input: '#form_step2_specific_price_sp_from_quantity ',
    leave_initial_price_checkbox: '#form_step2_specific_price_leave_bprice ',
    specific_product_price_input: '#form_step2_specific_price_sp_price ',
    specific_price_reduction_type_select: '#form_step2_specific_price_sp_reduction_type ',
    specific_price_reduction_tax_select: '#form_step2_specific_price_sp_reduction_tax ',
    specific_price_discount_input: '#form_step2_specific_price_sp_reduction ',
    specific_price_save_button: '#form_step2_specific_price_save ',
    specific_price_delete_button: '#js-specific-price-list i[text()="delete"]',
    pricing_first_priorities_select: '#form_step2_specificPricePriority_0',
    pricing_second_priorities_select: '#form_step2_specificPricePriority_1',
    pricing_third_priorities_select: '#form_step2_specificPricePriority_2',
    pricing_fourth_priorities_select: '#form_step2_specificPricePriority_3',
    product_SEO_tab: '#tab_step5 > a',
    SEO_meta_title: '#form_step5_meta_title_1',
    SEO_meta_description: '#form_step5_meta_description_1',
    SEO_friendly_url: '#form_step5_link_rewrite_1',
    product_options_tab: '#tab_step6 > a',
    options_visibility: '#form_step6_visibility',
    options_condition_select: '#form_step6_condition',
    options_isbn: '#form_step6_isbn',
    options_ean13: '#form_step6_ean13',
    options_upc: '#form_step6_upc',
    options_add_customization_field_button: '#custom_fields > a',
    options_first_custom_field_label: '#form_step6_custom_fields_0_label_1',
    options_first_custom_field_type: '#form_step6_custom_fields_0_type',
    options_first_custom_field_require: '#form_step6_custom_fields_0_require',
    options_second_custom_field_label: '#form_step6_custom_fields_1_label_1',
    options_second_custom_field_type: '#form_step6_custom_fields_1_type',
    options_add_new_file_button: '#step6 a[href="#collapsedForm"]',
    options_select_file: '#form_step6_attachment_product_file',
    options_add_virtual_product_file_button: '#form_step3_virtual_product_file ',
    options_file_name: '#form_step6_attachment_product_name',
    options_file_description: '#form_step6_attachment_product_description',
    options_file_add_button: '#form_step6_attachment_product_add',
    options_file_checkbox: '#form_step6_attachments_0 ',
    attached_file_checkbox: '#product-attachment-file tbody label[contains(text(),"%FileName")] input',
    catalog_product_table: '#product_catalog_list table.product',
    get catalog_product_name() {
      return this.catalog_product_table + ' > tbody tr:first-child > td:nth-child(4) > a';
    },
    get catalog_product_reference() {
      return this.catalog_product_table + ' > tbody tr:first-child > td:nth-child(5)';
    },
    get catalog_product_category() {
      return this.catalog_product_table + ' > tbody tr:first-child > td:nth-child(6)';
    },
    get catalog_product_price() {
      return this.catalog_product_table + ' > tbody tr:first-child > td:nth-child(7)';
    },
    get catalog_product_quantity() {
      return this.catalog_product_table + ' > tbody tr:first-child > td:nth-child(9)';
    },
    get catalog_product_online() {
      return this.catalog_product_table + ' > tbody tr:first-child > td:nth-child(10) > a > i';
    },
    get catalog_reset_filter() {
      return this.catalog_product_table + ' .column-filters button[name="products_filter_reset"]';
    },
    get catalog_submit_filter() {
      return this.catalog_product_table + '.column-filters button[name="products_filter_submit"]';
    },
    catalog_home: '#form_step1_categories ul li div label',
    catalog_first_element_radio: '#form_step1_categories ul li ul li:nth-child(1) div',
    catalog_second_element_radio: '#form_step1_categories ul li ul li:nth-child(2) div',
    category_radio_button: '#form_step1_categories input[type="checkbox"][value="%VALUE"]',
    category_radio: '#form_step1_categories label[text()[contains(.,"%S")]] input:nth-child(2)',
    preview_buttons: '#product_form_preview_btn',
    dropdown_button: '#dropdownMenu',
    duplicate_button: '[aria-labelledby="dropdownMenu"] a.duplicate',
    success_panel: 'div.alert-success p',
    delete_button: '#product_form_delete_btn',
    delete_confirmation_button: '#confirmation_modal .modal-dialog .modal-footer button:nth-child(%I)',
    confirmation_modal_content: '#confirmation_modal .modal-dialog div.modal-body',
    symfony_toolbar: '[id*=sfToolbarMainContent] > a',
    summary_tinymce_buttons: '#description_short div.mce-toolbar-grp',
    symfony_toolbar_block: '[id*=sfToolbarMainContent][style*="block"]',
    combination_table: '#accordion_combinations ',
    home_delete_button: '#ps_categoryTags span:nth-child(1) a',
    created_category: '#ps_categoryTags span:nth-child(2) span',
    preview_link: 'a',
    continue_confirmation: '#confirmation_modal button:nth-child(2)',
    search_categories: '#ps-select-product-category ',
    list_categories: '#ui-id-1 li',
    default_category: '#ps_categoryTags span:nth-child(1) a',
    image_combination_src: '#combination_%ID_id_image_attr img):nth-child(%POS)',
    img_added_product_pack: '#form_step1_inputPackItems-data li:nth-child(%ID) img',
    product_type_option: '#form_step1_type_product option:nth-child(%POS)',
    tax_rule_taux_standard_option: '#step2_id_tax_rules_group_rendered option:nth-child(5)',
    tax_rule_taux_standard_select: '#step2_id_tax_rules_group_rendered',
    predefined_value_option: '#form_step1_features_0_value option[text()="%V"]',
    predefined_value_select: '#form_step1_features_0_value',
    custom_value_input: '#form_step1_features_0_custom_value_1',
    background_picture: '#product-images-dropzone div.dz-image.bg',
    product_pack_items: '#form_step1_inputPackItems-data ',
    add_products_to_pack: '#js_form_step1_inputPackItems div',
    attribute_group_names: '#attributes-list a',
    attribute_value_checkbox: '#attribute-group-%ID div div:nth-child(%S) label',
    price_tax_included_input: '#form_step1_price_ttc_shortcut ',
    delete_feature_button: '#features-content a.delete:nth-child(%ID)',
    alert_button: '#confirmation_modal button.%B',
    product_language: '#form_switch_language',
    sales_button: '#product_form_go_to_sales',
    product_list_button: '#product_form_open_quicknav',
    help_button: '#product_form_open_help',
    tooltip_button: '#form div.product-header span.help-box',
    tooltip_box_content: ' div.popover-body',
    input_pack_item: '#js_form_step1_inputPackItems',
    calendar_form: '#calendar',
    right_sidebar: '#right-sidebar',
    tax_rule: '#select2-step2_id_tax_rules_group_rendered-container',
    category_checkbox: '#form_step1_categories label[text()[contains(.,"%CATEGORY")]] input:nth-child(1)):nth-child(1)',
    category_label: '#form_step1_categories label[text()[contains(.,"%CATEGORY")]]',
    brand_option: '#select2-form_step1_id_manufacturer-results li',
    tax_option: '#select2-step2_id_tax_rules_group_rendered-results li[contains(text(),"%V")]',
    product_type_value_option: '#form_step1_type_product option[value="%TYPE"]',
    quick_navigation_column: '#right-sidebar table thead th[contains(text(),"%TEXT")]',
    quick_navigation_columns: '#right-sidebar table thead th',
    quick_navigation_product_name_link: '#right-sidebar table tr td:nth-child(2) a',
    type_help_box_icon: '#form div.product-header span.help-box',
    quantity_help_box_icon: '#product_qty_0_shortcut_div span.help-box',
    help_box: '.popover-body',
    price_help_box_icon: '#step1 span.help-box[data-content*="price"]',
    product_type_select: '#form_step1_type_product',
    picture_element: '#product-images-dropzone > div:nth-child(%ID)',
    prodcut_picture_bloc: '#product-images-dropzone > div.disabled.openfilemanager',
    picture_save_image_settings_button: '#product-images-form button[contains(text(), "Save image settings")]',
    picture_cover_checkbox: '#form_image_cover',
    picture_legend_en_textarea: '#form_image_legend_1',
    picture_background: '.dz-preview  :not(.disable):nth-child(%POS)',
    picture_close_button: '#product-images-form > button',
    picture_zoom_button: '#product-images-form a.open-image',
    zoom_picture_close_button: 'button.mfp-close',
    zoom_picture_img: 'img.mfp-img',
    picture_delete_button: '#product-images-form button[contains(text(), "Delete")]',
    picture_cover_bloc: '( *.dz-preview")  :not(.disable):nth-child(%POS) div .iscover ',
    tab_summary: '#tab_description_short a',
    tiny_mce_buttons: '#mce_%ID',
    tiny_mce_validation_message: '#form_step1_description_short > ul.text-danger > li',
    delete_feature_icon: '#features-content a.delete i[text()= "delete"]):nth-child(%POS)',
    delete_brand_product_button: '#reset_brand_product',
    related_product_delete_icon: '#form_step1_related_products-data > li:nth-child(%I) > i',
    delete_related_product_button: '#reset_related_product',
    parent_category_select: '#select2-form_step1_new_category_id_parent-container',
    category_checkbox_input: '#form_step1_categories input[value="%ID"][type="checkbox"]',
    category_expand_button: '#categories-tree-expand',
    category_collapse_button: '#categories-tree-reduce',
    id_list_categories: '#ui-id-1',
    list_name_category: '#ui-id-1 > li:nth-child(%P) > a',
    tag_category: '#ps_categoryTags span[contains(text(),"%NAME")]',
    delete_tag_category: '#ps_categoryTags a[data-id="%ID"]',
    parent_category_option: '#select2-form_step1_new_category_id_parent-results li[text()="%N"]',
    main_category_radio_button: '#form_step1_categories input[name="ignore"][value="3"]',
    product_pricing_ttc_input: '#form_step2_price_ttc',
    product_pricing_ht_input: '#form_step2_price',
    product_unit_input: '#form_step2_unity',
    pricing_manage_tax_rules_link: '#step2 > a.external-link',
    on_sale_checkbox: '#form_step2_on_sale',
    banner_tax_included_span: '#final_retail_price_ti',
    banner_tax_excluded_span: '#final_retail_price_te',
    specific_price_for_currency_select: '#select2-form_step2_specific_price_sp_id_currency-container',
    specific_price_for_currency_option: '#select2-form_step2_specific_price_sp_id_currency-results li[text()="%C"]',
    specific_price_for_country_select: '#select2-form_step2_specific_price_sp_id_country-container',
    specific_price_for_country_search_input: ' span.select2-search > input[type="search"]',
    specific_price_for_country_option: '#select2-form_step2_specific_price_sp_id_country-results li[text()="%C"]',
    specific_price_for_group_select: '#select2-form_step2_specific_price_sp_id_group-container',
    specific_price_for_group_option: '#select2-form_step2_specific_price_sp_id_group-results li[text()="%C"]',
    specific_price_customer_input: '#form_step2_specific_price_sp_id_customer',
    specific_price_customer_option: '#specific_price_form > div.tt-menu div div:nth-child(1)',
    specific_price_available_from_input: '#form_step2_specific_price_sp_from',
    specific_price_to_input: '#form_step2_specific_price_sp_to',
    specific_price_cancel_button: '#form_step2_specific_price_cancel',
    apply_all_product_checkbox: '#form_step2_specificPricePriorityToAll',
    priority_selected_option: '#form_step2_specificPricePriority_%NB option[value="%P" and selected]',
    preview_bloc: '#serp div[class="%C"]',
    reset_url_button: '#seo-url-regenerate',
    redirection_select: '#form_step5_redirect_type',
    target_product_input: '#form_step5_id_type_redirected',
    target_product: '#id-product-redirected fieldset div div:nth-child(1) span div div div:nth-child(%I)',
    product_combination_block: '#show_variations_selector',
    product_virtual_tab: '#tab_step3 a[contains(text(),"Virtual product")]',
    virtual_delete_attached_file: '#form_step3_virtual_product_file_details > a.delete',
    virtual_download_attached_file: '#form_step3_virtual_product_file_details > a.download',
    product_quantity_tab: '#tab_step3 a[contains(text(),"Quantities")]',
    options_visibility_option: '#form_step6_visibility > option[value="%O"]',
    tag_input: '#form_step6_tags_1-tokenfield',
    options_online_only: '#form_step6_display_options_online_only',
    options_custom_field_label: '#form_step6_custom_fields_%R_label_1',
    options_custom_field_type: '#form_step6_custom_fields_%R_type',
    options_custom_field_require: '#form_step6_custom_fields_%R_require',
    delete_customization_field_icon: '#custom_fields > a.delete',
    options_available_for_order_checkbox: '#form_step6_display_options_available_for_order',
    options_show_price_checkbox: '#form_step6_display_options_show_price',
    options_show_condition_checkbox: '#form_step6_show_condition',
    attached_file_table: '#product-attachment-file',
    suppliers_table: '#form_step6_suppliers',
    suppliers_checkbox: '#form_step6_suppliers td:nth-child(1) label[contains(text(),"%FileName")] input',
    suppliers_radio_button: '#form_step6_suppliers td:nth-child(2) label[contains(text(),"%FileName")] input',
    suppliers_title: '#supplier_combination_collection > strong',
    supplier_reference_input: '#form_step6_supplier_combination_%V_0_supplier_reference',
    supplier_price_input: '#form_step6_supplier_combination_%V_0_product_price',
    supplier_currency_select: '#form_step6_supplier_combination_%V_0_product_price_currency',
    no_attached_file_message: '#step6 > div.js-options-no-attachments',
  },
  ProductList: {
    product_id: '#product_catalog_list .product tr:nth-child(%ID) td:nth-child(2) label',
    product_name: '#product_catalog_list tbody tr:nth-child(%ID) td:nth-child(4) a',
    product_reference: '#product_catalog_list tbody tr:nth-child(%ID) td:nth-child(5)',
    sort_by_icon: '#product_catalog_list div[data-sort-col-name="%B"] span[role="columnheader"]',
    sort_button: '#product_catalog_list div[data-sort-col-name="%B"] span[role="columnheader"]',
    price_tax_excluded_sort_button: '#product_catalog_list [data-sort-col-name="price"]:nth-child(1) span[role="columnheader"]',
    price_tax_included_sort_button: '#product_catalog_list [data-sort-col-name="price"]:nth-child(2) span[role="columnheader"]',
    status_select: '#product_filter_column_active select[name="filter_column_active"]',
    product_status: '#product_catalog_list tr:nth-child(%I) td:nth-child(10) a i.action-%ACTION',
    edit_button: '#product_catalog_list a.product-edit i:nth-child(1)',
    pagination_products: '#product_catalog_list div[class*=justify-content-center] > div:nth-of-type(1)',
    dropdown_button: '#product_catalog_list tbody tr:nth-child(%POS) div.btn-group-action button[data-toggle="dropdown"]',
    action_preview_button: '#product_catalog_list tbody tr:nth-child(%POS) div.btn-group-action a[target="_blank"]',
    action_duplicate_button: '#product_catalog_list tbody tr:nth-child(%POS) div.btn-group-action a[onclick*="duplicate"]',
    action_delete_button: '#product_catalog_list tbody tr:nth-child(%POS) div.btn-group-action a[onclick*="delete"]',
    delete_now_modal_button: '#catalog_deletion_modal button[value="confirm"]',
    search_no_results: '#product_catalog_list tbody tr:nth-child(1) td',
    pagination_next: '#pagination_next_url ',
    pagination_previous: '#product_catalog_list li.page-item previous  a',
    page_active_number: '#product_catalog_list li.page-item.active input',
    item_per_page: '#paginator_select_page_limit ',
    product_category: '#product_catalog_list div tr:nth-child(%I) td:nth-child(6)',
    reset_button: '#product_catalog_list tr:nth-child(2) th:nth-child(9) button[name="products_filter_reset"]',
    status_filter: '#product_filter_column_active select[name="filter_column_active"]',
    item_per_page_select: '#paginator_select_page_limit',
    search_product_button: 'button[name="filter_column_name"]',
    products_column: '#product_catalog_list table tr:nth-child(%ID) td:nth-child(%COL)',
    products_status_icon: '#product_catalog_list table tr:nth-child(%ID) td:nth-child(10) i',
    products_paginator_select: '#paginator_select_page_limit',
    catalogue_filter_by_reference_input: 'input[name="filter_column_reference"]',
    catalogue_filter_by_category_input: 'input[name="filter_column_name_category"]',
    catalogue_filter_by_price_min_input: 'input#filter_column_price_min',
    catalogue_filter_by_price_max_input: 'input#filter_column_price_max',
    catalogue_filter_by_quantity_min_input: 'input[id*="quantity_min"]',
    catalogue_filter_by_quantity_max_input: 'input[id*="quantity_max"]',
    catalogue_filter_by_id_min_input: 'input[id*="id_product_min"]',
    catalogue_filter_by_id_max_input: 'input[id*="id_product_max"]',
    catalogue_filter_by_status: '[id*="product_filter"] option[value="%id"]',
    change_product_status: '#product_catalog_list tbody tr:nth-child(%ID) td:nth-child(10) a',
    product_status_icon: '#product_catalog_list table tr:nth-child(%TR) td:nth-child(10) i.action-%STATUS',
    filter_by_category_button: '#product_catalog_category_tree_filter button',
    expand_filter_link: '#product_catalog_category_tree_filter_expand ',
    unselect_filter_link: '#product_catalog_category_tree_filter_reset ',
    filter_list_category_label: '#product_categories_categories > ul.category-tree  > li > ul > li:nth-child(%ID) div label',
    sub_category_label: '#product_categories_categories ul.category-tree ul li:nth-child(%I) ul li:nth-child(%J) label.category-label ',
    category_radio: '#product_categories_categories label:nth-child(%I)',
    categories_radio: '#product_categories_categories label'
  }
};
