module.exports = {
  Employee: {
    new_employee_button: '#page-header-desc-employee-new_employee',
    first_name_input: '#firstname',
    last_name_input: '#lastname',
    email_input: '#email',
    password_input: '#passwd',
    profile_select: '#id_profile',
    save_button: '#employee_form_submit_btn',
    orders_page: '#subtab-AdminParentOrders a',
    email_search_input: '[name="employeeFilter_email"]',
    search_button_team: '#submitFilterButtonemployee',
    search_result: '.badge',
    team_employee_name: '#form-employee tbody td:nth-child(3)',
    team_employee_last_name: '#form-employee tbody td:nth-child(4)',
    team_employee_email: '#form-employee tbody td:nth-child(5)',
    team_employee_profile: '#form-employee tbody td:nth-child(6)',
    reset_search_button: '[name="submitResetemployee"]',
    dropdown_toggle: '#form-employee tbody button',
    delete_link: '#form-employee tbody li a',
    edit_button: '#table-employee a .edit',
    language_select: '#id_lang ',
    selected_language_option: '#id_lang option[selected="selected"]',
    employee_column_information: '#employee_grid tr:nth-of-type(1) > td:nth-of-type(%COL)',
  }
};
