module.exports = {
  Installation: {
    language_select: '#langList',
    next_step_button: '#btNext',
    agree_terms_and_conditions_button: '#set_license',
    compatibility_green_box: '#sheet_system" |  #sheet_ h3.okBlock',
    shop_name_input: '#infosShop',
    country_select: '#infosCountry_chosen',
    search_country_input: '#infosCountry_chosen div[class*=chosen-search] > input',
    country_france_option: '#infosCountry_chosen div ul li',
    first_name_input: '#infosFirstname',
    last_name_input: '#infosName',
    email_address_input: '#infosEmail',
    shop_password_input: '#infosPassword',
    retype_password_input: '#infosPasswordRepeat',
    database_address_input: '#dbServer',
    database_name_input: '#dbName',
    database_login_input: '#dbLogin',
    database_password_input: '#dbPassword',
    test_connection_button: '#btTestDB',
    create_DB_button: '#btCreateDB',
    created_DB_bloc: '#dbResultCheck',
    create_file_parameter_step: ' li#process_step_generateSettingsFile.process_step.success',
    create_database_step: ' li#process_step_installDatabase.process_step.success',
    create_default_shop_step: ' li#process_step_installDefaultData.process_step.success',
    create_database_table_step: ' li#process_step_populateDatabase.process_step.success',
    create_shop_informations_step: ' li#process_step_configureShop.process_step.success',
    create_demonstration_data_step: ' li#process_step_installFixtures.process_step.success',
    install_module_step: ' li#process_step_installModules.process_step.success',
    install_addons_modules_step: ' li#process_step_installModulesAddons.process_step.success',
    install_theme_step: ' li#process_step_installTheme.process_step.success',
    finish_step: '#install_process_success div:nth-child(1) h2',
    finished_installation_msg: '#install_process_success h2',
    prestashop_download_button: 'a .btn-success:nth-child(1)',
    download_version: '#node-81380 div div:nth-child(2) div div div div:nth-child(3) a:nth-child(2)',
    refresh_button: '#req_bt_refresh'
  }
};
