module.exports = {
  FeatureSubMenu: {
    add_new_feature: '#page-header-desc-feature-new_feature ',
    name_input: '#name_1 ',
    save_button: '#feature_form_submit_btn ',
    search_input: '#table-feature th input[name="featureFilter_%SEARCHBY"] , #table-feature input[name="feature_valueFilter_%SEARCHBY"]',
    search_button: '#submitFilterButtonfeature , #submitFilterButtonfeature_value',
    selected_feature: "#table-feature tr:last-of-type td [title='View']",
    feature_select: '#id_feature ',
    add_value_button: '#page-header-desc-feature_value-new_feature_value , #page-header-desc-feature-new_feature_value ',
    value_input: '#value_1 ',
    save_value_button: '#feature_value_form_submit_btn ',
    select_option: '#table-feature button[data-toggle="dropdown"]',
    update_feature_button: '#table-feature a.edit ',
    update_feature_value_button: '#table-feature_value tr:nth-child(%ID) a.edit',
    delete_feature: '#table-feature a.delete ',
    reset_button: '#table-feature button[name="submitResetfeature"]',
    feature_checkbox: '#table-feature input[type="checkbox"]',
    feature_bulk_actions: '#bulk_action_menu_feature ',
    feature_delete_bulk_action: '#form-feature div.bulk-actions li:nth-child(4) a',
    save_then_add_another_value_button: ' *[name="submitAddfeature_valueAndStay"]',
    dropdown_option: '#table-feature_value td:nth-child(4) button.dropdown-toggle',
    delete_button: '#table-feature_value td:nth-child(4) a[onclick*="Delete"]',
    view_button: '#table-feature td:nth-child(6) a [title="View"]',
    features_number_span: '#form-feature span.badge ',
    value_search_input: '#table-feature_value input[name="feature_valueFilter_%SEARCHBY"]',
    value_search_button: '#submitFilterButtonfeature_value ',
    value_column: '#table-feature_value tbody tr:nth-child(%ID) td:nth-child(%B)',
    value_reset_button: '#table-feature_value button[name="submitResetfeature_value"]',
    back_to_list_button: '#desc-feature_value-back ',
    feature_table: '#table-feature ',
    feature_column: '#table-feature tbody tr:nth-child(%ID) td:nth-child(%B)',
    feature_sort_icon: '#table-feature span[contains(text(),"%B")] a:nth-child(%W)'
  }
};
