#!/bin/sh

PHP_BINARY=`which php`
STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.php`
PROJECT_PATH=$(cd "$( dirname "$0" )/../../" && pwd)

# Determine if a file list is passed
if [ "$#" -eq 1 ]
then
  oIFS=$IFS
  IFS='
    '
  SFILES="$1"
  IFS=$oIFS
fi
SFILES=${SFILES:-$STAGED_FILES_CMD}


echo "Checking PHP Lint..."
for FILE in $SFILES
do
  $PHP_BINARY -l -d display_errors=0 $PROJECT_PATH/$FILE
  if [ $? != 0 ]
  then
    echo "Error(s), please fix it before commit."
    exit 1
  fi
done

echo "Running PHP CS Fixer..."
$PHP_BINARY ./vendor/bin/php-cs-fixer fix

exit $?
