module.exports = {
  Pages: {
    Common: {
      success_panel: '//*[@id="content"]/div[@class="bootstrap"]/div[contains(@class, "success")] | //*[contains(@class,"alert-success")]//*[contains(@class,"alert-text")]/p',
      alert_panel: '//*[@id="content"]/div[@class="bootstrap"]/div[contains(@class, "alert")] | //*[contains(@class,"alert-danger")]//*[contains(@class,"alert-text")]/p'
    },
    Category: {
      enable_display_option: 'label[for="cms_page_category_is_displayed_1"]',
      meta_description_input: '#cms_page_category_meta_description_1',
      name_input: '#cms_page_category_name_1',
      add_category_button: '#page-header-desc-configuration-add_cms_category',
      parent_category_select_option: '//select[@name="id_parent"]/option[contains(text(), "%CATEGORY_NAME")]',
      parent_category_select: '[name="cms_page_category[parent_category]"][value="%V"]',
      expand_button: '#cms_page_category_parent_category span',
      description_textarea: '#cms_page_category_description_1',
      meta_title_input: '#cms_page_category_meta_title_1',
      meta_keywords_input: '#cms_page_category_meta_keywords_1-tokenfield',
      parent_category: '//*[@id="cms_category_form"]//select[@name="id_parent"]',
      save_button: '.card-footer .float-right button',
      name_filter: '#cms_page_category_name',
      view_button: '//*[@id="cms_page_category_grid_table"]//a[@data-original-title="View"]',
      dropdown_toggle: '#cms_page_category_grid tbody [data-toggle="dropdown"]',
      edit_button: '#cms_page_category_grid_table a[href*="edit"]',
      search_name_result: '//*[@id="cms_page_category_grid_table"]//tbody//td[%ID]',
      delete_button: '#cms_page_category_grid_table a[data-method="DELETE"]',
      bulk_actions_button: '#cms_page_category_grid button.js-bulk-actions-btn',
      bulk_actions_select_all_button: '//*[@id="cms_page_category_grid_bulk_action_select_all"]/..',
      bulk_actions_delete_button: '#cms_page_category_grid_bulk_action_delete_bulk',
      bulk_actions_disable_button: '#cms_page_category_grid_bulk_action_disable_selection',
      bulk_actions_enable_button: '#cms_page_category_grid_bulk_action_enable_selection',
      home_icon: '#cms_page_category_grid_panel .card-footer a'
    },
    Page: {
      enable_display_option: 'label[for="cms_page_is_displayed_1"]',
      title_input: '#cms_page_title_1',
      meta_title_input: '#cms_page_meta_title_1',
      meta_description_input: '#cms_page_meta_description_1',
      page_category: '[name="cms_page[page_category_id]"][value="%V"]',
      add_new_page_button: '#page-header-desc-configuration-add_cms_page',
      meta_keywords_input: '#cms_page_meta_keyword_1-tokenfield',
      delete_tag_button: '(//div[@class="token"]//a)[%POS]',
      enable_indexation_option: '//label[@for="cms_page_is_indexed_for_search_1"]',
      save_button: '//*[@id="cms_form_submit_btn"]',
      save_and_preview_button: '.card-footer button[name="save-and-preview"]',
      title_filter_input: '#cms_page_meta_title',
      search_title_result: '//*[@id="cms_page_grid_table"]//tbody//td[%ID]',
      edit_button: '//*[@id="cms_page_grid_table"]//a[@data-original-title="Edit"]',
      dropdown_toggle: '#cms_page_grid_table a[data-toggle="dropdown"]',
      delete_button: '#cms_page_grid_table  a[data-method="DELETE"]',
      page_content: '#cms_page_content_1_ifr',
      bulk_actions_button: '#cms_page_grid .js-bulk-actions-btn',
      bulk_actions_select_all_button: '//*[@id="cms_page_grid_bulk_action_select_all"]/..',
      bulk_actions_delete_button: '#cms_page_grid_bulk_action_delete_bulk',
      bulk_actions_disable_button: '#cms_page_grid_bulk_action_disable_selection',
      bulk_actions_enable_button: '#cms_page_grid_bulk_action_enable_selection',
      reset_button: 'button[name="cms_page[actions][reset]"]',
      category_option: '//*[@id="cms_page_page_category_id"]//label[text()[contains(.,"%CATEGORY_NAME")]][1]/input',
      cancel_button: '.card-footer a.btn',
      expand_button: '#cms_page_page_category_id span',
    }
  }
};
