admin_customer_groups_index:
  path: /
  methods: [ GET ]
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\Configure\ShopParameters\CustomerGroupsController::indexAction'
    _legacy_controller: AdminGroups
    _legacy_link: AdminGroups
    _legacy_feature_flag: customer_group

admin_customer_groups_search:
  path: /
  methods: POST
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\CommonController::searchGridAction
    gridDefinitionFactoryServiceId: prestashop.core.grid.definition.factory.customer_groups
    redirectRoute: admin_customer_groups_index
    _legacy_controller: AdminGroups
    _legacy_link: AdminGroups:submitFiltergroup
    _legacy_feature_flag: customer_group

admin_customer_groups_create:
  path: /new
  methods: [ GET, POST ]
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\Configure\ShopParameters\CustomerGroupsController::createAction'
    _legacy_controller: AdminGroups
    _legacy_link: AdminGroups:addgroup
    _legacy_feature_flag: customer_group

admin_customer_groups_edit:
  path: /{groupId}/edit
  methods: [ GET, POST ]
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\Configure\ShopParameters\CustomerGroupsController::editAction'
    _legacy_controller: AdminGroups
    _legacy_link: AdminGroups:updategroup
    _legacy_feature_flag: customer_group
  requirements:
    groupId: \d+

admin_customer_groups_toggle_show_prices:
  path: /{groupId}/toggle-show-prices
  methods: [ POST ]
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\Configure\ShopParameters\CustomerGroupsController::toggleShowPricesAction'
    _legacy_controller: AdminGroups
    _legacy_link: AdminGroups:changeShowPricesValgroup
    _legacy_feature_flag: customer_group
    _legacy_parameters:
      id_group: groupId
  requirements:
    groupId: \d+

admin_customer_groups_delete:
  path: /{groupId}/delete
  methods: [ POST, DELETE ]
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\Configure\ShopParameters\CustomerGroupsController::deleteAction'
    _legacy_controller: AdminGroups
    _legacy_link: AdminGroups:deletegroup
    _legacy_feature_flag: customer_group
    _legacy_parameters:
      id_group: groupId
  requirements:
    groupId: \d+

admin_customer_groups_bulk_delete:
  path: /bulk-delete
  methods: [ POST, DELETE ]
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\Configure\ShopParameters\CustomerGroupsController::bulkDeleteAction'
    _legacy_controller: AdminGroups
    _legacy_link: AdminGroups:submitBulkdeletegroup
    _legacy_feature_flag: customer_group

admin_customer_groups_save_default_groups:
  path: /save-default-groups
  methods: [ POST ]
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\Configure\ShopParameters\CustomerGroupsController::saveDefaultGroupsAction'
    _legacy_controller: AdminGroups
    _legacy_link: AdminGroups:process
    _legacy_feature_flag: customer_group
