admin_customer_b2b_list:
  path: /
  methods: [ GET ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\CustomerB2b\CustomerB2bController::listAction
    _legacy_controller: AdminCustomersB2B
    _legacy_link: AdminCustomersB2B
