#!/bin/bash

PROJECT_PATH=$(cd "$( dirname "$0" )/../" && pwd)

FILES=$PROJECT_PATH/tests/Selenium/errorShots/*
for f in $FILES
do
  echo "--- Displaying content of $f ...\n"

  echo "data:image/png;base64,$(base64 -w 0 $f)"
done
