#!/bin/bash

HAS_DIFF=$(diff composer.json ./tests/composer.json.travis)

if [ -n "$HAS_DIFF" ]
then
  if ! $TRAVIS_PULL_REQUEST
  then
      cd $TRAVIS_BUILD_DIR
      composer update  --prefer-dist --no-interaction --no-progress
      git config --global user.name "Travis-CI"
      git config --global user.email "travis@travis-ci.org"

      git clone https://$GITHUB_OAUTH_TOKEN@github.com/$TRAVIS_REPO_SLUG --branch=$TRAVIS_BRANCH /var/www/new_repo
      cd /var/www/new_repo
      git remote rm origin
      git remote add origin https://$GITHUB_OAUTH_TOKEN@github.com/$TRAVIS_REPO_SLUG

      cp $TRAVIS_BUILD_DIR/composer.json ./tests/composer.json.travis
      cp $TRAVIS_BUILD_DIR/composer.lock ./tests/composer.lock.travis
      cp $TRAVIS_BUILD_DIR/composer.lock /var/www/prestashop.unit.test/composer.lock
      git commit ./tests/composer.json.travis ./tests/composer.lock.travis -q -m "Auto-update composer.lock"
      git push -fq origin $TRAVIS_BRANCH
      cd /var/www/prestashop.unit.test
  else
      rm composer.lock
  fi
fi