#!/bin/bash

rm -Rf /var/www/prestashop.unit.test
cp -Rf $TRAVIS_BUILD_DIR/fresh_install /var/www/prestashop.unit.test
chmod 777 -R /var/www
mysql -uroot -e "drop database \`prestashop\`"
mysqladmin -uroot create prestashop
mysql -uroot prestashop < $TRAVIS_BUILD_DIR/db.sql
