#!/bin/bash

PROJECT_PATH=$(cd "$( dirname "$0" )/../" && pwd)

bash $PROJECT_PATH/travis-scripts/install-prestashop

echo "* Installing functional tests ...";

cd $PROJECT_PATH/tests/E2E && npm install

echo "* Running functional tests ...";
npm test -- --MODULE=ps_legalcompliance
exit $?
