#!/bin/bash

/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_10.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :10 -ac -screen 0 1600x1200x16
cd /var/www/prestashop.unit.test/tests/Selenium
mv settings.travis.js settings.js
export PATH=$PATH:/usr/lib/jvm/java-8-oracle/jre/bin
npm install
DISPLAY=:10 npm run selenium &> /dev/null &
sleep 5
npm test
status=$?
cd $TRAVIS_BUILD_DIR
exit $status
