#!/bin/bash

if [[ $EXTRA_TESTS != *"functionnal"* ]]; then
  exit 0
fi

echo "* Installing functionnal tests ...";

git clone https://github.com/PrestaShop/PSFunctionalTests.git
cd $TRAVIS_BUILD_DIR/PSFunctionalTests && npm install && cd test/itg/1.7

echo "* Running functionnal tests ...";
$TRAVIS_BUILD_DIR/PSFunctionalTests/node_modules/mocha/bin/mocha index.webdriverio.js -c --URL=localhost  --MODULE=None --SAUCELABS=None -t 200000
exit $?