module.exports = {
  accountPage: {
    create_button: '[data-link-action="display-register-form"]',
    firstname_input: '#customer-form input[name=firstname]',
    lastname_input: '#customer-form input[name=lastname]',
    email_input: '#customer-form input[name=email]',
    password_input: '[name="password"]',
    birthday_input: '[name="birthday"]',
    checkout_step: '#checkout-personal-information-step h1',
    checkout_step_complete: '#checkout-personal-information-step.-complete',
    checkout_step_identity: '#checkout-personal-information-step .identity',
    alert_danger_email: '#customer-form li.alert alert-danger ',
    continue_shopping: '#main div.cart-grid a',
    customer_form_continue_button: '#customer-form button[name="continue"]',
    save_account_button: '#customer-form button[data-link-action="save-customer"]',
    gender_radio_button: '#customer-form label:nth-child(2)  input[name*="id_gender"]',
    account_link: '#_desktop_user_info a .account ',
    add_first_address: '#address-link',
    adr_address: '#content input[name=address1]',
    adr_postcode: '#content input[name=postcode]',
    adr_city: '#content input[name=city]',
    adr_save: '#content footer > button',
    success_alert: '[data-alert="success"]',
    adr_update: '[data-link-action="edit-address"]',
    name_firstname_link: '#_desktop_user_info a .account ',
    selected_country_option_list: ' *[name="id_country option[selected and (text()="%D")]',
    selected_default_country_option_list: ' *[name="id_country option[selected and not(disabled)]',
    /*------------------ connect with existing account from checkout ----------------*/
    sign_tab: '#checkout-personal-information-step a [contains(text(), "Sign in")]',
    signin_email_input: '#login-form input[name=email]',
    signin_password_input: '#login-form input[name="password"]',
    continue_button: '#login-form button.continue',
    /*---------------------- create account from checkout -------------------------*/
    new_customer_btn: '[data-link-action="register-new-customer"]',
    new_address_btn: '[name="confirm-addresses"]',
    new_email_input: '#customer-form input[name=email]',
    password_account_input: '#customer-form input[name=password]',
    new_password_input: '#customer-form input[name="new_password"]',
    customer_form: '#customer-form ',
    shipping_continue_btn: '#js-delivery button[name="confirmDeliveryOption"]',
    pay_by_check: '#payment-option-1 ',
    terms_of_service: '#conditions_to_approve[terms-and-conditions]"]',
    order_button: '#payment-confirmation button',
    confirmed_order_message: '#content-hook_order_confirmation h3.card-title',
    email_sent_message: '#content-hook_order_confirmation p',
    save_notification: '#notifications li',
    danger_alert: '#customer-form li.alert-danger',
    add_new_address: '#checkout-addresses-step p.add-address a',
    /*---------------------- address management -------------------------*/
    address_firstname_input: '.js-address-form input[name=firstname]',
    address_lastname_input: '.js-address-form input[name=lastname]',
    delete_address_button: '#main article.address"])[1] a [data-link-action="delete-address"]',
    address_block: 'article.address',
    create_new_address_button: '#content a [data-link-action="add-address"]',
    country_list: '#content select[name="id_country"]',
    country_option: '#content select[name="id_country option[text()="%B"]',
    last_name_input: '#content input[name="lastname"]',
    first_name_input: '#content input[name="firstname"]',
    address1_input: '#content input[name="address1"]',
    address2_input: '#content input[name="address2"]',
    dni_input: '#content input[name="dni"]',
    poste_code_input: '#content input[name="postcode"]',
    city_input: '#content input[name="city"]',
    phone_input: '#content input[name="phone"]',
    date_birthday_input: '#content input[name="birthday"]',
    personal_information_tab: '#checkout-personal-information-step h1',
    address_country_list: '#content select[name="id_country"]',
  }
};
