# Common service from bundle that are needed in Admin and in Front (like some Entity repositories)
services:
  _defaults:
    public: false

  PrestaShop\PrestaShop\Adapter\Security\NativeAdminSessionReader: ~

  PrestaShop\PrestaShop\Adapter\Security\AdminPathProvider: ~

  # // TODO <cnc> ===== Front admin bar ===== AdminBarPageContextFactory service definition - TODO
  # Remove "public: true" when the bar will no longer retrieve the service from the FrontController.
  PrestaShop\PrestaShop\Adapter\AdminBar\AdminBarActionUrlProvider:
    arguments:
      - '@PrestaShop\PrestaShop\Adapter\Security\AdminPathProvider'
    public: true

  PrestaShop\PrestaShop\Adapter\AdminBar\ProductAdminBarResourceProvider:
    tags:
      - { name: 'prestashop.admin_bar.resource_provider', controller: ProductController }

  PrestaShop\PrestaShop\Adapter\AdminBar\CategoryAdminBarResourceProvider:
    tags:
      - { name: 'prestashop.admin_bar.resource_provider', controller: CategoryController }

  PrestaShop\PrestaShop\Adapter\AdminBar\CmsAdminBarResourceProvider:
    tags:
      - { name: 'prestashop.admin_bar.resource_provider', controller: CmsController }

  # // TODO <cnc> ===== Front admin bar ===== AdminBarPageContextFactory service definition - TODO
  # Remove "public: true" when the bar will no longer retrieve the service from the FrontController.
  PrestaShop\PrestaShop\Adapter\AdminBar\AdminBarPageContextFactory:
    arguments:
      $resourceProviders: !tagged_locator { tag: prestashop.admin_bar.resource_provider, index_by: controller }
    public: true

  PrestaShop\PrestaShop\Adapter\AdminBar\AdminBarPermissionChecker:
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'

  PrestaShop\PrestaShop\Adapter\AdminBar\ProductAdminBarActionProvider:
    tags: [ 'prestashop.admin_bar.action_provider' ]
    arguments:
      $translator: '@=service("prestashop.adapter.legacy.context").getContext().getTranslator()'
    autowire: true

  PrestaShop\PrestaShop\Adapter\AdminBar\CategoryAdminBarActionProvider:
    tags: [ 'prestashop.admin_bar.action_provider' ]
    arguments:
      $translator: '@=service("prestashop.adapter.legacy.context").getContext().getTranslator()'
    autowire: true

  PrestaShop\PrestaShop\Adapter\AdminBar\CmsAdminBarActionProvider:
    tags: [ 'prestashop.admin_bar.action_provider' ]
    arguments:
      $translator: '@=service("prestashop.adapter.legacy.context").getContext().getTranslator()'
    autowire: true

  PrestaShop\PrestaShop\Adapter\AdminBar\AdminBarActionResolver:
    arguments:
      $providers: !tagged_iterator prestashop.admin_bar.action_provider
      $hookManager: '@PrestaShop\PrestaShop\Adapter\HookManager'
    public: true

  PrestaShop\PrestaShop\Core\Security\AdminSessionReaderInterface:
    alias: PrestaShop\PrestaShop\Adapter\Security\NativeAdminSessionReader

  PrestaShop\PrestaShop\Adapter\Security\AdminEmployeeContextProvider:
    arguments:
      - '@PrestaShop\PrestaShop\Core\Security\AdminSessionReaderInterface'
      - '@prestashop.adapter.legacy.configuration'
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'
    public: true

  PrestaShopBundle\Entity\Repository\FeatureFlagRepository:
    factory: [ '@doctrine.orm.default_entity_manager', getRepository ]
    arguments:
      - PrestaShopBundle\Entity\FeatureFlag
    lazy: true

  PrestaShopBundle\Entity\Repository\ShipmentRepository:
    factory: [ '@doctrine.orm.default_entity_manager', getRepository ]
    arguments:
      - PrestaShopBundle\Entity\Shipment
    calls:
      - setTablePrefix: [ '%database_prefix%' ]
    lazy: true
    public: true

  PrestaShopBundle\Entity\Repository\TabRepository:
    factory: [ '@doctrine.orm.default_entity_manager', getRepository ]
    arguments:
      - PrestaShopBundle\Entity\Tab
    lazy: true

  prestashop.adapter.order.repository.order_repository:
    alias: PrestaShop\PrestaShop\Adapter\Order\Repository\OrderRepository
    deprecated:
      package: PrestaShop\PrestaShop
      version: 9.0

  PrestaShop\PrestaShop\Adapter\Order\Repository\OrderRepository:
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'

  PrestaShop\PrestaShop\Adapter\Shop\Repository\ShopRepository:
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'

  PrestaShop\PrestaShop\Adapter\Carrier\Repository\CarrierRepository:
    arguments:
      - '@PrestaShop\PrestaShop\Adapter\Shop\Repository\ShopRepository'
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'

  PrestaShop\PrestaShop\Adapter\Order\Repository\OrderDetailRepository:
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'

  PrestaShop\PrestaShop\Adapter\Shipment\OrderShipmentService:
    public: true
    arguments:
      - '@PrestaShopBundle\Entity\Repository\ShipmentRepository'
      - '@PrestaShop\PrestaShop\Adapter\Order\Repository\OrderRepository'
      - '@PrestaShop\PrestaShop\Adapter\Carrier\Repository\CarrierRepository'
