services:
  _defaults:
    public: true
    autowire: true
    autoconfigure: true

  PrestaShopBundle\EventSubscriber\:
    resource: "%kernel.project_dir%/src/PrestaShopBundle/EventSubscriber/*"
    lazy: true
