services:
  _defaults:
    autowire: true

  PrestaShopBundle\Service\Csp\CspTabToggler: ~

  PrestaShopBundle\EventListener\Admin\CspFeatureFlagListener:
    autowire: true
    tags:
      - { name: doctrine.orm.entity_listener, event: postUpdate, entity: PrestaShopBundle\Entity\FeatureFlag, lazy: true }
