services:
  _defaults:
    public: true

  prestashop.core.module.configuration.payment_restrictions_configurator:
    class: PrestaShop\PrestaShop\Core\Module\Configuration\PaymentRestrictionsConfigurator
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'
      - '@=service("prestashop.adapter.legacy.context").getContext().shop.id'
      - '@prestashop.adapter.module.payment_module_provider'

  PrestaShop\PrestaShop\Core\Module\ModuleRepository:
    lazy: true
    autowire: true
    arguments:
      - '@PrestaShop\PrestaShop\Adapter\Module\ModuleDataProvider'
      - '@PrestaShop\PrestaShop\Adapter\Module\AdminModuleDataProvider'
      - '@doctrine.cache.provider'
      - '@PrestaShop\PrestaShop\Adapter\HookManager'
      - "@=service('prestashop.adapter.legacy.configuration').get('_PS_MODULE_DIR_')"

  prestashop.core.admin.module.repository.eventsubscriber:
    class: PrestaShop\PrestaShop\Core\Module\EventSubscriber
    arguments:
      - '@PrestaShop\PrestaShop\Core\Module\ModuleRepository'
      - '@PrestaShop\PrestaShop\Adapter\Cache\Clearer\SymfonyCacheClearer'
    tags:
      - { name: kernel.event_subscriber }

  PrestaShop\PrestaShop\Core\Module\ModuleManager:
    autowire: true
    arguments:
      $moduleDataProvider: '@PrestaShop\PrestaShop\Adapter\Module\ModuleDataProvider'
      $adminModuleDataProvider: '@PrestaShopBundle\Service\DataProvider\Admin\ModuleInterface'
      $hookManager: '@prestashop.adapter.hook.manager'
      $modulesDir: '%prestashop.module_dir%'
      $xliffFileLoader: '@translation.loader.xliff'

  PrestaShop\PrestaShop\Core\Module\SourceHandler\ZipSourceHandler:
    autowire: true
    arguments:
      $modulePath: '%prestashop.module_dir%'
    tags: [ core.module.source_handler ]

  PrestaShop\PrestaShop\Core\Module\SourceHandler\RemoteZipSourceHandler:
    autowire: true
    public: false
    arguments:
      $downloadDir: '%ps_cache_dir%/downloads'
    tags: [ core.module.source_handler ]

  PrestaShop\PrestaShop\Core\Module\SourceHandler\SourceHandlerFactory:
    arguments:
      - !tagged core.module.source_handler

  prestashop.module.factory.sourcehandler:
    alias: PrestaShop\PrestaShop\Core\Module\SourceHandler\SourceHandlerFactory
    public: true
    deprecated:
      package: PrestaShop\PrestaShop
      version: 8.1

  prestashop.module.sourcehandler.zip:
    alias: PrestaShop\PrestaShop\Core\Module\SourceHandler\ZipSourceHandler
    public: true
    deprecated:
      package: PrestaShop\PrestaShop
      version: 8.1

  prestashop.module.manager:
    alias: PrestaShop\PrestaShop\Core\Module\ModuleManager
    public: true
    deprecated:
      package: PrestaShop\PrestaShop
      version: 8.1

  PrestaShop\PrestaShop\Core\Module\ModuleOverrideChecker:
    arguments:
      - '@translator'
      - !php/const _PS_OVERRIDE_DIR_
