tinymce.addI18n('fi',{
"Redo": "Tee uudelleen",
"Undo": "Peru",
"Cut": "Leikkaa",
"Copy": "Kopioi",
"Paste": "Liit\u00e4",
"Select all": "Valitse kaikki",
"New document": "Uusi dokumentti",
"Ok": "Ok",
"Cancel": "Peruuta",
"Visual aids": "Visuaaliset neuvot",
"Bold": "Lihavointi",
"Italic": "Kursivointi",
"Underline": "Alleviivaus",
"Strikethrough": "Yliviivaus",
"Superscript": "Yl\u00e4indeksi",
"Subscript": "Alaindeksi",
"Clear formatting": "Poista muotoilu",
"Align left": "Tasaa vasemmalle",
"Align center": "Keskit\u00e4",
"Align right": "Tasaa oikealle",
"Justify": "Tasaa",
"Bullet list": "J\u00e4rjest\u00e4m\u00e4t\u00f6n lista",
"Numbered list": "J\u00e4rjestetty lista",
"Decrease indent": "Sisenn\u00e4",
"Increase indent": "Loitonna",
"Close": "Sulje",
"Formats": "Muotoilut",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "Selaimesi ei tue leikep\u00f6yd\u00e4n suoraa k\u00e4ytt\u00e4mist\u00e4. Ole hyv\u00e4 ja k\u00e4yt\u00e4 n\u00e4pp\u00e4imist\u00f6n Ctrl+X\/C\/V n\u00e4pp\u00e4inyhdistelmi\u00e4.",
"Headers": "Otsikot",
"Header 1": "Otsikko 1",
"Header 2": "Otsikko 2",
"Header 3": "Otsikko 3",
"Header 4": "Otsikko 4",
"Header 5": "Otsikko 5",
"Header 6": "Otsikko 6",
"Headings": "Otsikot",
"Heading 1": "Otsikko 1",
"Heading 2": "Otsikko 2",
"Heading 3": "Otsikko 3",
"Heading 4": "Otsikko 4",
"Heading 5": "Otsikko 5",
"Heading 6": "Otsikko 6",
"Preformatted": "Preformatted",
"Div": "Div",
"Pre": "Esimuotoiltu",
"Code": "Koodi",
"Paragraph": "Kappale",
"Blockquote": "Lainauslohko",
"Inline": "Samalla rivill\u00e4",
"Blocks": "Lohkot",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Liitt\u00e4minen on nyt pelk\u00e4n tekstin -tilassa. Sis\u00e4ll\u00f6t liitet\u00e4\u00e4n nyt pelkk\u00e4n\u00e4 tekstin\u00e4, kunnes otat vaihtoehdon pois k\u00e4yt\u00f6st\u00e4.",
"Font Family": "Fontti",
"Font Sizes": "Fonttikoko",
"Class": "Luokka",
"Browse for an image": "Selaa kuvia",
"OR": "TAI",
"Drop an image here": "Pudota kuva t\u00e4h\u00e4n",
"Upload": "Vie",
"Block": "Lohko",
"Align": "Tasaa",
"Default": "Oletus",
"Circle": "Pallo",
"Disc": "Ympyr\u00e4",
"Square": "Neli\u00f6",
"Lower Alpha": "pienet kirjaimet: a, b, c",
"Lower Greek": "pienet kirjaimet: \u03b1, \u03b2, \u03b3",
"Lower Roman": "pienet kirjaimet: i, ii, iii",
"Upper Alpha": "isot kirjaimet: A, B, C",
"Upper Roman": "isot kirjaimet: I, II, III",
"Anchor": "Ankkuri",
"Name": "Nimi",
"Id": "Id",
"Id should start with a letter, followed only by letters, numbers, dashes, dots, colons or underscores.": "Id voi alkaa kirjaimella, sen j\u00e4lkeen voi k\u00e4ytt\u00e4\u00e4 kirjaimia, numeroja, viivoja, pisteit\u00e4, kaksoispistett\u00e4 ja alaviivausta",
"You have unsaved changes are you sure you want to navigate away?": "Sinulla on tallentamattomia muutoksia, haluatko varmasti siirty\u00e4 toiselle sivulle?",
"Restore last draft": "Palauta aiempi luonnos",
"Special character": "Erikoismerkki",
"Source code": "L\u00e4hdekoodi",
"Insert\/Edit code sample": "Lis\u00e4\u00e4\/muokkaa koodiesimerkki",
"Language": "Kieli",
"Code sample": "Koodiesimerkki",
"Color": "V\u00e4ri",
"R": "R",
"G": "G",
"B": "B",
"Left to right": "Vasemmalta oikealle",
"Right to left": "Oikealta vasemmalle",
"Emoticons": "Hymi\u00f6t",
"Document properties": "Dokumentin ominaisuudet",
"Title": "Otsikko",
"Keywords": "Avainsanat",
"Description": "Kuvaus",
"Robots": "Robotit",
"Author": "Tekij\u00e4",
"Encoding": "Merkist\u00f6",
"Fullscreen": "Koko ruutu",
"Action": "Toiminto",
"Shortcut": "Oikotie",
"Help": "Ohje",
"Address": "Osoite",
"Focus to menubar": "Kohdistus valikkoon",
"Focus to toolbar": "Kohdistus ty\u00f6kalupalkkiin",
"Focus to element path": "Kohdistus elementtiin",
"Focus to contextual toolbar": "Kohdistus kontekstuaaliseen ty\u00f6kalupalkkiin",
"Insert link (if link plugin activated)": "Lis\u00e4\u00e4 linkki (jos linkki-liit\u00e4nn\u00e4inen aktiivinen)",
"Save (if save plugin activated)": "Tallenna (jos tallenna-liit\u00e4nn\u00e4inen aktiivinen)",
"Find (if searchreplace plugin activated)": "Etsi (jos etsikorvaa-liit\u00e4nn\u00e4inen aktiivinen)",
"Plugins installed ({0}):": "Asennetut liit\u00e4nn\u00e4iset ({0}):",
"Premium plugins:": "Premium liit\u00e4nn\u00e4iset:",
"Learn more...": "Lis\u00e4tietoja...",
"You are using {0}": "K\u00e4yt\u00e4t {0}",
"Plugins": "Liit\u00e4nn\u00e4iset",
"Handy Shortcuts": "K\u00e4tev\u00e4t pikan\u00e4pp\u00e4imet",
"Horizontal line": "Vaakasuora viiva",
"Insert\/edit image": "Lis\u00e4\u00e4\/muokkaa kuva",
"Image description": "Kuvaus",
"Source": "L\u00e4hde",
"Dimensions": "Mittasuhteet",
"Constrain proportions": "S\u00e4ilyt\u00e4 mittasuhteet",
"General": "Yleiset",
"Advanced": "Lis\u00e4asetukset",
"Style": "Tyyli",
"Vertical space": "Vertikaalinen tila",
"Horizontal space": "Horisontaalinen tila",
"Border": "Reunus",
"Insert image": "Lis\u00e4\u00e4 kuva",
"Image": "Kuva",
"Image list": "Kuvalista",
"Rotate counterclockwise": "Kierr\u00e4 vastap\u00e4iv\u00e4\u00e4n",
"Rotate clockwise": "Kierr\u00e4 my\u00f6t\u00e4p\u00e4iv\u00e4\u00e4n",
"Flip vertically": "K\u00e4\u00e4nn\u00e4 pystysuunnassa",
"Flip horizontally": "K\u00e4\u00e4nn\u00e4 vaakasuunnassa",
"Edit image": "Muokkaa kuvaa",
"Image options": "Kuvan asetukset",
"Zoom in": "L\u00e4henn\u00e4",
"Zoom out": "Loitonna",
"Crop": "Rajaa valintaan",
"Resize": "Kuvan koon muutos",
"Orientation": "Suunta",
"Brightness": "Kirkkaus",
"Sharpen": "Ter\u00e4vyys",
"Contrast": "Kontrasti",
"Color levels": "V\u00e4ritasot",
"Gamma": "Gamma",
"Invert": "K\u00e4\u00e4nteinen",
"Apply": "Aseta",
"Back": "Takaisin",
"Insert date\/time": "Lis\u00e4\u00e4 p\u00e4iv\u00e4m\u00e4\u00e4r\u00e4 tai aika",
"Date\/time": "P\u00e4iv\u00e4m\u00e4\u00e4r\u00e4\/aika",
"Insert link": "Lis\u00e4\u00e4 linkki",
"Insert\/edit link": "Lis\u00e4\u00e4\/muokkaa linkki",
"Text to display": "N\u00e4ytett\u00e4v\u00e4 teksti",
"Url": "Osoite",
"Target": "Kohde",
"None": "Ei mit\u00e4\u00e4n",
"New window": "Uusi ikkuna",
"Remove link": "Poista linkki",
"Anchors": "Ankkurit",
"Link": "Linkki",
"Paste or type a link": "Sijoita tai kirjoita linkki",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "Antamasi osoite n\u00e4ytt\u00e4\u00e4 olevan s\u00e4hk\u00f6postiosoite. Haluatko lis\u00e4t\u00e4 osoitteeseen vaaditun mailto: -etuliitteen?",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "Antamasi osoite n\u00e4ytt\u00e4\u00e4 olevan ulkoinen linkki. Haluatko lis\u00e4t\u00e4 osoitteeseen vaaditun http:\/\/ -etuliitteen?",
"Link list": "Linkkilista",
"Insert video": "Lis\u00e4\u00e4 video",
"Insert\/edit video": "Lis\u00e4\u00e4\/muokkaa video",
"Insert\/edit media": "Lis\u00e4\u00e4\/muokkaa media",
"Alternative source": "Vaihtoehtoinen l\u00e4hde",
"Poster": "L\u00e4hett\u00e4j\u00e4",
"Paste your embed code below:": "Liit\u00e4 upotuskoodisi alapuolelle:",
"Embed": "Upota",
"Media": "Media",
"Nonbreaking space": "Sitova v\u00e4lily\u00f6nti",
"Page break": "Sivunvaihto",
"Paste as text": "Liit\u00e4 tekstin\u00e4",
"Preview": "Esikatselu",
"Print": "Tulosta",
"Save": "Tallenna",
"Find": "Etsi",
"Replace with": "Korvaa",
"Replace": "Korvaa",
"Replace all": "Korvaa kaikki",
"Prev": "Edel.",
"Next": "Seur.",
"Find and replace": "Etsi ja korvaa",
"Could not find the specified string.": "Haettua merkkijonoa ei l\u00f6ytynyt.",
"Match case": "Erota isot ja pienet kirjaimet",
"Whole words": "Koko sanat",
"Spellcheck": "Oikolue",
"Ignore": "\u00c4l\u00e4 huomioi",
"Ignore all": "\u00c4l\u00e4 huomioi mit\u00e4\u00e4n",
"Finish": "Lopeta",
"Add to Dictionary": "Lis\u00e4\u00e4 sanakirjaan",
"Insert table": "Lis\u00e4\u00e4 taulukko",
"Table properties": "Taulukon ominaisuudet",
"Delete table": "Poista taulukko",
"Cell": "Solu",
"Row": "Rivi",
"Column": "Sarake",
"Cell properties": "Solun ominaisuudet",
"Merge cells": "Yhdist\u00e4 solut",
"Split cell": "Jaa solu",
"Insert row before": "Lis\u00e4\u00e4 rivi ennen",
"Insert row after": "Lis\u00e4\u00e4 rivi j\u00e4lkeen",
"Delete row": "Poista rivi",
"Row properties": "Rivin ominaisuudet",
"Cut row": "Leikkaa rivi",
"Copy row": "Kopioi rivi",
"Paste row before": "Liit\u00e4 rivi ennen",
"Paste row after": "Liit\u00e4 rivi j\u00e4lkeen",
"Insert column before": "Lis\u00e4\u00e4 rivi ennen",
"Insert column after": "Lis\u00e4\u00e4 rivi j\u00e4lkeen",
"Delete column": "Poista sarake",
"Cols": "Sarakkeet",
"Rows": "Rivit",
"Width": "Leveys",
"Height": "Korkeus",
"Cell spacing": "Solun v\u00e4li",
"Cell padding": "Solun tyhj\u00e4 tila",
"Caption": "Seloste",
"Left": "Vasen",
"Center": "Keskell\u00e4",
"Right": "Oikea",
"Cell type": "Solun tyyppi",
"Scope": "Laajuus",
"Alignment": "Tasaus",
"H Align": "H tasaus",
"V Align": "V tasaus",
"Top": "Yl\u00e4reuna",
"Middle": "Keskikohta",
"Bottom": "Alareuna",
"Header cell": "Otsikkosolu",
"Row group": "Riviryhm\u00e4",
"Column group": "Sarakeryhm\u00e4",
"Row type": "Rivityyppi",
"Header": "Otsikko",
"Body": "Runko",
"Footer": "Alaosa",
"Border color": "Reunuksen v\u00e4ri",
"Insert template": "Lis\u00e4\u00e4 pohja",
"Templates": "Pohjat",
"Template": "Pohja",
"Text color": "Tekstin v\u00e4ri",
"Background color": "Taustan v\u00e4ri",
"Custom...": "Mukauta...",
"Custom color": "Mukautettu v\u00e4ri",
"No color": "Ei v\u00e4ri\u00e4",
"Table of Contents": "Sis\u00e4llysluettelo",
"Show blocks": "N\u00e4yt\u00e4 lohkot",
"Show invisible characters": "N\u00e4yt\u00e4 n\u00e4kym\u00e4tt\u00f6m\u00e4t merkit",
"Words: {0}": "Sanat: {0}",
"{0} words": "{0} sanaa",
"File": "Tiedosto",
"Edit": "Muokkaa",
"Insert": "Lis\u00e4\u00e4",
"View": "N\u00e4yt\u00e4",
"Format": "Muotoilu",
"Table": "Taulukko",
"Tools": "Ty\u00f6kalut",
"Powered by {0}": "Tehty {0}:ll\u00e4",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Rikastetun tekstin alue. Paina ALT-F9 valikkoon. Paina ALT-F10 ty\u00f6kaluriviin. Paina ALT-0 ohjeeseen."
});