'use strict';

module.exports = {
  languages: {
    English: {
      "Andorra": "ca",
      "United Arab Emirates": "ar",
      "Afghanistan": "fa, ps",
      "Antigua and Barbuda": "en",
      "Anguilla": "en",
      "Albania": "sq",
      "Armenia": "hy",
      "Angola": "pt",
      "Antarctica": "en, es, fr, ru",
      "Argentina": "es",
      "American Samoa": "en, sm",
      "Austria": "de",
      "Australia": "en",
      "Aruba": "nl, pap",
      "Aland Islands": "sv",
      "Azerbaijan": "az",
      "Bosnia and Herzegovina": "bs, hr, sr",
      "Barbados": "en",
      "Bangladesh": "bn",
      "Belgium": "nl, fr, de",
      "Burkina Faso": "fr",
      "Bulgaria": "bg",
      "Bahrein": "ar",
      "Burundi": "fr",
      "Benin": "fr",
      "Saint-Barthélemy": "fr",
      "Bermuda": "en",
      "Brunei Darussalam": "ms",
      "Bolivia": "es, qu, gn, ay",
      "Caribbean Netherlands": "nl",
      "Brazil": "pt",
      "Bahamas": "en",
      "Bhutan": "dz",
      "Bouvet Island": "no",
      "Botswana": "en, tn",
      "Belarus": "be, ru",
      "Belize": "en",
      "Canada": "en, fr",
      "Cocos (Keeling) Islands": "en",
      "Democratic Republic of the Congo": "fr",
      "Centrafrican Republic": "fr, sg",
      "Republic of the Congo": "fr",
      "Switzerland": "de, fr, it, rm",
      "Côte d'Ivoire": "fr",
      "Cook Islands": "en, rar",
      "Chile": "es",
      "Cameroon": "fr, en",
      "China": "zh-hans",
      "Colombia": "es",
      "Costa Rica": "es",
      "Cuba": "es",
      "Cabo Verde": "pt",
      "Curaçao": "nl, en",
      "Christmas Island": "en",
      "Cyprus": "el, tr",
      "Czech Republic": "cs",
      "Germany": "de",
      "Djibouti": "fr, ar, so, aa",
      "Denmark": "da",
      "Dominica": "en",
      "Dominican Republic": "es",
      "Algeria": "ar",
      "Ecuador": "es",
      "Estonia": "et",
      "Egypt": "ar",
      "Western Sahara": "ar, es, fr",
      "Eritrea": "ti, ar, en",
      "Spain": "ast, ca, es, eu, gl",
      "Ethiopia": "am, om",
      "Finland": "fi, sv, se",
      "Fiji": "en",
      "Falkland Islands": "en",
      "Micronesia": "en",
      "Faroe Islands": "fo, da",
      "France": "fr",
      "Gabon": "fr",
      "United Kingdom": "en, ga, cy, gd, kw",
      "Grenada": "en",
      "Georgia": "ka",
      "French Guiana": "fr",
      "Guernsey": "en",
      "Ghana": "en",
      "Gibraltar": "en",
      "Greenland": "kl, da",
      "The Gambia": "en",
      "Guinea": "fr",
      "Guadeloupe": "fr",
      "Equatorial Guinea": "es, fr, pt",
      "Greece": "el",
      "South Georgia and the South Sandwich Islands": "en",
      "Guatemala": "es",
      "Guam": "en, ch",
      "Guinea Bissau": "pt",
      "Guyana": "en",
      "Hong Kong": "zh-hant, en",
      "Heard Island and McDonald Islands": "en",
      "Honduras": "es",
      "Croatia": "hr",
      "Haiti": "fr, ht",
      "Hungary": "hu",
      "Indonesia": "id",
      "Ireland": "en, ga",
      "Israel": "he",
      "Isle of Man": "en",
      "India": "hi, en",
      "British Indian Ocean Territory": "en",
      "Iraq": "ar, ku",
      "Iran": "fa",
      "Iceland": "is",
      "Italia": "it, de, fr",
      "Jersey": "en",
      "Jamaica": "en",
      "Jordan": "ar",
      "Japan": "ja",
      "Kenya": "sw, en",
      "Kyrgyzstan": "ky, ru",
      "Cambodia": "km",
      "Kiribati": "en",
      "Comores": "ar, fr, sw",
      "Saint Kitts and Nevis": "en",
      "North Korea": "ko",
      "South Korea": "ko, en",
      "Kuweit": "ar",
      "Cayman Islands": "en",
      "Kazakhstan": "kk, ru",
      "Laos": "lo",
      "Lebanon": "ar, fr",
      "Saint Lucia": "en",
      "Liechtenstein": "de",
      "Sri Lanka": "si, ta",
      "Liberia": "en",
      "Lesotho": "en, st",
      "Lithuania": "lt",
      "Luxembourg": "lb, fr, de",
      "Latvia": "lv",
      "Libya": "ar",
      "Morocco": "fr, zgh, ar",
      "Monaco": "fr",
      "Moldova": "ro, ru, uk",
      "Montenegro": "srp, sr, hr, bs, sq",
      "Saint Martin": "fr",
      "Madagascar": "mg, fr",
      "Marshall Islands": "en, mh",
      "Macedonia": "mk",
      "Mali": "fr",
      "Myanmar": "my",
      "Mongolia": "my",
      "Macao": "zh-hant, pt",
      "Northern Mariana Islands": "en, ch",
      "Martinique": "fr",
      "Mauritania": "ar, fr",
      "Montserrat": "en",
      "Malta": "mt, en",
      "Mauritius": "mfe, fr, en",
      "Maldives": "dv",
      "Malawi": "en, ny",
      "Mexico": "es",
      "Malaysia": "ms",
      "Mozambique": "pt",
      "Namibia": "en, sf, de",
      "New Caledonia": "fr",
      "Niger": "fr",
      "Norfolk Island": "en, pih",
      "Nigeria": "en",
      "Nicaragua": "es",
      "The Netherlands": "nl",
      "Norway": "nb, nn, no, se",
      "Nepal": "ne",
      "Nauru": "na, en",
      "Niue": "niu, en",
      "New Zealand": "mi, en",
      "Oman": "ar",
      "Panama": "es",
      "Peru": "es",
      "French Polynesia": "fr",
      "Papua New Guinea": "en, tpi, ho",
      "Philippines": "en, tl",
      "Pakistan": "en, ur",
      "Poland": "pl",
      "Saint Pierre and Miquelon": "fr",
      "Pitcairn": "en, pih",
      "Puerto Rico": "es, en",
      "Palestinian Territory": "ar, he",
      "Portugal": "pt",
      "Palau": "en, pau, ja, sov, tox",
      "Paraguay": "es, gn",
      "Qatar": "ar",
      "Reunion": "fr",
      "Romania": "ro",
      "Serbia": "sr, sr-Latn",
      "Russia": "ru",
      "Rwanda": "rw, fr, en",
      "Saudi Arabia": "ar",
      "Solomon Islands": "en",
      "Seychelles": "fr, en, crs",
      "Sudan": "ar, en",
      "Sweden": "sv",
      "Singapore": "zh-hans, en, ms, ta",
      "Saint Helena": "en",
      "Slovenia": "sl",
      "Svalbard and Jan Mayen": "no",
      "Slovakia": "sk",
      "Sierra Leone": "en",
      "San Marino": "it",
      "Sénégal": "fr",
      "Somalia": "so, ar",
      "Suriname": "nl",
      "São Tomé and Príncipe": "pt",
      "South Sudan": "en",
      "El Salvador": "es",
      "Syria": "ar",
      "Swaziland": "en, ss",
      "Turks and Caicos Islands": "en",
      "Chad": "fr, ar",
      "French Southern and Antarctic Lands": "fr",
      "Togo": "fr",
      "Thailand": "th",
      "Tajikistan": "tg, ru",
      "Tokelau": "tkl, en, sm",
      "Timor-Leste": "pt, tet",
      "Turkmenistan": "tk",
      "Tunisia": "ar, fr",
      "Tonga": "en",
      "Turkey": "tr",
      "Trinidad and Tobago": "en",
      "Tuvalu": "en",
      "Taiwan": "zh-hant",
      "Tanzania": "sw, en",
      "Ukraine": "uk",
      "Uganda": "en, sw",
      "United States": "en",
      "Uruguay": "es",
      "Uzbekistan": "uz, kaa",
      "City of the Vatican": "it",
      "Saint Vincent and the Grenadines": "en",
      "Venezuela": "es",
      "British Virgin Islands": "en",
      "United States Virgin Islands": "en",
      "Vietnam": "vi",
      "Vanuatu": "bi, en, fr",
      "Wallis and Futuna": "fr",
      "Samoa": "sm, en",
      "Yemen": "ar",
      "Mayotte": "fr",
      "South Africa": "en, af, st, tn, xh, zu",
      "Zambia": "en",
      "Zimbabwe": "en, sn, nd",
    },
    Frensh: {
      "Emirats arabes unis": "ar",
      "France": "fr",
      "États-Unis": "en",
      "Italie": "it, de, fr",
      "Ukraine": "uk",
      "Turquie": "tr",
      "Tunisie": "ar, fr",
      "Soudan": "ar, en",
      "Russie": "ru",
      "Jamaïque": "en",
      "Finlande": "fi, sv, se",
    }
  }
};
