services:
  _defaults:
    public: true
    bind:
      $connection: '@doctrine.dbal.default_connection'
      $dbPrefix: '%database_prefix%'

  prestashop.adapter.contact.repository:
    class: 'PrestaShop\PrestaShop\Adapter\Support\ContactRepository'

  PrestaShop\PrestaShop\Adapter\Support\ContactDeleter:
    public: false

  prestashop.adapter.contact.deleter:
    alias: 'PrestaShop\PrestaShop\Adapter\Support\ContactDeleter'
    deprecated:
      package: PrestaShop\PrestaShop
      version: 9.0

  prestashop.adapter.contact.query_handler.get_contact_for_editing:
    class: 'PrestaShop\PrestaShop\Adapter\Contact\QueryHandler\GetContactForEditingHandler'
    autoconfigure: true
    arguments:
      - '@PrestaShopBundle\Form\DataTransformer\StringArrayToIntegerArrayDataTransformer'

  prestashop.adapter.contact.command_handler.edit_contact:
    class: 'PrestaShop\PrestaShop\Adapter\Contact\CommandHandler\EditContactHandler'
    autoconfigure: true
    arguments:
      - '@validator'

  prestashop.adapter.contact.command_handler.add_contact:
    class: 'PrestaShop\PrestaShop\Adapter\Contact\CommandHandler\AddContactHandler'
    autoconfigure: true
    arguments:
      - '@validator'

  PrestaShop\PrestaShop\Adapter\Contact\Repository\ContactRepository:
    autowire: true
    public: false

  PrestaShop\PrestaShop\Core\Domain\Contact\CommandHandler\DeleteContactHandler:
    autowire: true
    public: false
    autoconfigure: true

  PrestaShop\PrestaShop\Core\Domain\Contact\CommandHandler\BulkDeleteContactHandler:
    autowire: true
    public: false
    autoconfigure: true
