services:
  _defaults:
    autowire: true
    public: false

  PrestaShop\PrestaShop\Adapter\Discount\CommandHandler\AddDiscountHandler:
    autoconfigure: true

  PrestaShop\PrestaShop\Adapter\Discount\CommandHandler\DeleteDiscountHandler:
    autoconfigure: true

  PrestaShop\PrestaShop\Adapter\Discount\CommandHandler\UpdateDiscountHandler:
    autoconfigure: true

  PrestaShop\PrestaShop\Adapter\Discount\CommandHandler\BulkUpdateDiscountsStatusHandler:
    autoconfigure: true

  PrestaShop\PrestaShop\Adapter\Discount\CommandHandler\BulkDeleteDiscountsHandler:
    autoconfigure: true

  PrestaShop\PrestaShop\Adapter\Discount\CommandHandler\DuplicateDiscountHandler:
    autoconfigure: true

  PrestaShop\PrestaShop\Adapter\Discount\Update\DiscountBuilder:
    autoconfigure: true

  PrestaShop\PrestaShop\Adapter\Discount\Update\Filler\DiscountFiller:
    autoconfigure: true

  PrestaShop\PrestaShop\Adapter\Discount\Update\DiscountConditionsUpdater:
    autoconfigure: true
    arguments:
      $dbPrefix: '%database_prefix%'

  PrestaShop\PrestaShop\Adapter\Discount\Update\DiscountDuplicator:
    autoconfigure: true
    arguments:
      $dbPrefix: '%database_prefix%'

  PrestaShop\PrestaShop\Adapter\Discount\QueryHandler\GetDiscountForEditingHandler:
    autoconfigure: true

  PrestaShop\PrestaShop\Adapter\Discount\QueryHandler\GetDiscountTypesHandler:
    autoconfigure: true

  PrestaShop\PrestaShop\Adapter\Discount\Validate\DiscountValidator:
    calls:
      - setDiscountRepository: [ '@PrestaShop\PrestaShop\Adapter\Discount\Repository\DiscountRepository' ]

  PrestaShop\PrestaShop\Adapter\Discount\Repository\DiscountRepository:
    arguments:
      $connection: '@doctrine.dbal.default_connection'
      $dbPrefix: '%database_prefix%'

  PrestaShop\PrestaShop\Adapter\Discount\Repository\DiscountTypeRepository:
    arguments:
      $connection: '@doctrine.dbal.default_connection'
      $dbPrefix: '%database_prefix%'

  PrestaShop\PrestaShop\Adapter\Discount\Application\DiscountApplicationService:
    public: true
    arguments:
      $discountTypeRepository: '@PrestaShop\PrestaShop\Adapter\Discount\Repository\DiscountTypeRepository'

  prestashop.adapter.discount.priority:
    class: PrestaShop\PrestaShop\Core\Domain\Discount\ValueObject\DiscountPriority
    public: true
