services:
  _defaults:
    public: true
    autowire: true
    autoconfigure: true

  PrestaShop\PrestaShop\Core\Domain\Store\Repository\StoreRepository:
    public: false
    arguments:
      $connection: '@doctrine.dbal.default_connection'
      $dbPrefix: '%database_prefix%'

  PrestaShop\PrestaShop\Adapter\Store\HoursEncoder: ~

  PrestaShop\PrestaShop\Adapter\Store\QueryHandler\GetStoreForEditingHandler:
    arguments:
      $imageTagSourceParser: '@prestashop.core.image.parser.image_tag_source_parser'

  PrestaShop\PrestaShop\Adapter\Store\CommandHandler\AddStoreHandler: ~

  PrestaShop\PrestaShop\Adapter\Store\CommandHandler\EditStoreHandler: ~

  PrestaShop\PrestaShop\Adapter\Store\CommandHandler\ToggleStoreStatusHandler: ~

  PrestaShop\PrestaShop\Adapter\Store\CommandHandler\BulkUpdateStoreStatusHandler: ~

  PrestaShop\PrestaShop\Adapter\Store\CommandHandler\DeleteStoreHandler: ~

  PrestaShop\PrestaShop\Adapter\Store\CommandHandler\BulkDeleteStoreHandler: ~

  PrestaShop\PrestaShop\Adapter\Image\Uploader\StoreImageUploader: ~

  PrestaShop\PrestaShop\Adapter\Store\ContactDetailsConfiguration:
    arguments:
      - '@prestashop.adapter.legacy.configuration'
      - '@prestashop.adapter.shop.context'
      - '@prestashop.adapter.multistore_feature'

  # deprecated
  prestashop.core.domain.store.repository.store_repository:
    alias: PrestaShop\PrestaShop\Core\Domain\Store\Repository\StoreRepository
    deprecated:
      package: PrestaShop\PrestaShop
      version: 9.0
