		<Package>
			<PackagingType>
				<Code>[[PackagingTypeCode]]</Code>
				<Description>Prestashop Product</Description>
			</PackagingType>
			<Description>Rate</Description>
			<Dimensions>
				<UnitOfMeasurement>
					<Code>[[DimensionUnit]]</Code>
				</UnitOfMeasurement>
				<Width>[[Width]]</Width>
				<Height>[[Height]]</Height>
				<Length>[[Length]]</Length>
			</Dimensions>
			<PackageWeight>
				<UnitOfMeasurement>
					<Code>[[WeightUnit]]</Code>
				</UnitOfMeasurement>
				<Weight>[[PackageWeight]]</Weight>
			</PackageWeight>
		</Package>
