<?php
/**
 * For the full copyright and license information, please view the
 * docs/licenses/LICENSE.txt file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Tests\Unit\PrestaShopBundle\Resources;

use PHPUnit\Framework\TestCase;
use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;
use RegexIterator;
use SplFileInfo;
use Twig\Environment;
use Twig\Loader\FilesystemLoader;

/**
 * The admin theme's `public/` directory is generated by webpack and excluded from git, so a checkout
 * whose assets have not been built has none of it. Including one of those files without
 * `ignore_missing` turns that into a Twig LoaderError, which the back office renders as a 500 - on the
 * login page as well, so the shop is unreachable rather than merely unstyled.
 */
class AdminAssetBuildArtifactIncludeTest extends TestCase
{
    private const VIEWS_DIR = __DIR__ . '/../../../../src/PrestaShopBundle/Resources/views';

    /**
     * Matches a reference to a generated asset in either Twig form, capturing the whole construct so it
     * can be rendered as written: the `include()`/`source()` functions inside `{{ }}`, and the `include`
     * tag - which spells its escape hatch `ignore missing` rather than `ignore_missing`, so a fix applied
     * to one form does not carry over to the other.
     */
    private const INCLUDE_PATTERN = '#\{\{\s*(?:include|source)\(\s*\'@AdminNewTheme/[^\']+\'.*?\)\s*\}\}'
        . '|\{%\s*include\s+\'@AdminNewTheme/[^\']+\'.*?%\}#s';

    public function testEveryGeneratedAssetIncludeSurvivesAnUnbuiltAdminTheme(): void
    {
        $includes = $this->collectGeneratedAssetIncludes();

        // Guards against the pattern silently matching nothing after a refactor, which would make
        // every assertion below vacuous.
        self::assertNotEmpty($includes, 'No @AdminNewTheme include found - the pattern needs updating.');

        $twig = new Environment($this->loaderForAnUnbuiltTheme(), ['cache' => false]);

        foreach ($includes as [$file, $construct]) {
            try {
                $twig->createTemplate($construct)->render([]);
            } catch (\Twig\Error\LoaderError $e) {
                self::fail(sprintf(
                    '%s hard-requires a generated asset: %s%sPass ignore_missing = true (function form) '
                    . 'or ignore missing (tag form) so an unbuilt checkout still renders. Twig said: %s',
                    $file,
                    $construct,
                    PHP_EOL,
                    $e->getMessage()
                ));
            }
        }
    }

    /**
     * @return array<array{0: string, 1: string}> file path (relative to the views dir) and construct
     */
    private function collectGeneratedAssetIncludes(): array
    {
        $found = [];
        $files = new RegexIterator(
            new RecursiveIteratorIterator(new RecursiveDirectoryIterator(self::VIEWS_DIR)),
            '#\.html\.twig$#'
        );

        /** @var SplFileInfo $file */
        foreach ($files as $file) {
            if (!preg_match_all(self::INCLUDE_PATTERN, (string) file_get_contents($file->getPathname()), $matches)) {
                continue;
            }
            foreach ($matches[0] as $construct) {
                $found[] = [
                    ltrim(str_replace((string) realpath(self::VIEWS_DIR), '', (string) $file->getRealPath()), '/'),
                    $construct,
                ];
            }
        }

        return $found;
    }

    /**
     * An empty directory stands for `admin-dev/themes/new-theme` before `make assets` has run: the
     * namespace resolves, nothing under it exists.
     */
    private function loaderForAnUnbuiltTheme(): FilesystemLoader
    {
        $unbuiltTheme = sys_get_temp_dir() . '/ps-unbuilt-admin-theme-' . getmypid();
        if (!is_dir($unbuiltTheme) && !mkdir($unbuiltTheme, 0777, true) && !is_dir($unbuiltTheme)) {
            self::fail(sprintf('Could not create %s', $unbuiltTheme));
        }

        $loader = new FilesystemLoader();
        $loader->addPath($unbuiltTheme, 'AdminNewTheme');

        return $loader;
    }
}
