name: Add Issue to Project

on:
  issues:
    types: [ opened ]

jobs:
  add-to-project:
    uses: PrestaShop/.github/.github/workflows/reusable-add-to-project.yml@master
    with:
      project-number: 48
    secrets:
      TOKEN: ${{ secrets.JARVIS_TOKEN }}
