name: Normalize Dependabot PR
on:
  pull_request:
    types: [opened, synchronize]
    # author: dependabot[bot]

concurrency:
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  normalize:
    name: Normalize Dependabot PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Normalize Dependabot PR
        uses: tleon/.github/.github/actions/normalize-dependabot-pr@Issue-40559-normalize-dependabot-pr
