<?php $this->displayTemplate('header') ?>

<script type="text/javascript">
<!--
var default_iso = '<?php echo $this->session->shop_country ?>';
-->
</script>

<!-- Configuration form -->
<div id="infosShopBlock">
	<h2><?php echo $this->l('Shop settings and merchant account information') ?></h2>

	<!-- Shop name -->
	<div class="field clearfix">
		<label for="infosShop" class="aligned"><?php echo $this->l('Shop name:') ?> </label>
		<span class="contentinput">
			<input class="text required" type="text" id="infosShop" name="shop_name" value="<?php echo htmlspecialchars($this->session->shop_name) ?>" /> <sup class="required">*</sup>
		</span>
		<?php echo $this->displayError('shop_name') ?>
	</div>

	<!-- Activity -->
	<div class="field clearfix">
		<label for="infosActivity" class="aligned"><?php echo $this->l('Main activity:') ?></label>
		<span class="contentinput">
			<select id="infosActivity" name="shop_activity">
				<option value="0" <?php if (!$this->session->shop_activity): ?>selected="selected"<?php endif; ?>><?php echo $this->l('-- Please choose your main activity --') ?></option>
				<?php foreach ($this->list_activities as $i => $activity): ?>
					<option value="<?php echo $activity ?>" <?php if ($this->session->shop_activity == $activity): ?>selected="selected"<?php endif; ?>><?php echo $activity ?></option>
				<?php endforeach; ?>
				<option value="0"><?php echo $this->l('Other activity...') ?></option>
			</select>
		</span>
		<p class="userInfos aligned"><?php echo $this->l('This information is not required, it will only be used for statistical purposes. This information does not change anything in your store.') ?></p>
	</div>

	<!-- Country list -->
	<div class="field clearfix">
		<label for="infosCountry" class="aligned"><?php echo $this->l('Default country:') ?></label>
		<span class="contentinput">
			<select name="shop_country" id="infosCountry">
				<option><?php echo $this->l('-- Select your country --') ?></option>
				<?php foreach ($this->language->getCountries() as $iso => $country_name): ?>
					<option value="<?php echo $iso ?>" <?php if ($this->session->shop_country == $iso): ?>selected="selected"<?php endif; ?>><?php echo $country_name ?></option>
				<?php endforeach; ?>
			</select>
			<sup class="required">*</sup>
		</span>
		<?php echo $this->displayError('shop_country') ?>
	</div>

	<!-- Timezone list -->
	<div class="field clearfix">
		<label for="infosTimezone" class="aligned"><?php echo $this->l('Shop timezone:') ?></label>
		<span class="contentinput">
			<select name="shop_timezone" id="infosTimezone">
				<option><?php echo $this->l('-- Select your timezone --') ?></option>
				<?php foreach ($this->getTimezones() as $timezone): ?>
					<option value="<?php echo $timezone ?>" <?php if ($this->session->shop_timezone == $timezone): ?>selected="selected"<?php endif; ?>><?php echo $timezone ?></option>
				<?php endforeach; ?>
			</select>
			<sup class="required">*</sup>
		</span>
		<?php echo $this->displayError('shop_timezone') ?>
	</div>

	<!-- Shop logo -->
	<div class="field clearfix">
			<label for="infosLogo" class="aligned logo"><?php echo $this->l('Shop logo:') ?></label>
			<span class="contentinput">
				<p id="alignedLogo"><img id="uploadedImage" src="<?php echo __PS_BASE_URI__ ?>img/logo.jpg" alt="Logo" /></p>
			</span>
			<p class="userInfos aligned"><?php echo $this->l('Recommended dimensions:') ?><br />230px x 75px</p>

			<span id="inputFileLogo" class="contentinput">
				<input type="file" name="fileToUpload" id="fileToUpload"/>
			</span>
		<span id="resultInfosLogo" class="result"></span>
	</div>

	<!-- Admin firstname -->
	<div class="field clearfix">
		<label for="infosFirstname" class="aligned"><?php echo $this->l('First name:') ?> </label>
		<span class="contentinput">
			<input class="text required" type="text" id="infosFirstname" name="admin_firstname" value="<?php echo htmlspecialchars($this->session->admin_firstname) ?>" />
			<sup class="required">*</sup>
		</span>
		<?php echo $this->displayError('admin_firstname') ?>
	</div>

	<!-- Admin lastname -->
	<div class="field clearfix">
		<label for="infosName" class="aligned"><?php echo $this->l('Last name:') ?> </label>
		<span class="contentinput">
			<input class="text required" type="text" id="infosName" name="admin_lastname" value="<?php echo htmlspecialchars($this->session->admin_lastname) ?>" />
			<sup class="required">*</sup>
		</span>
		<?php echo $this->displayError('admin_lastname') ?>
	</div>

	<!-- Admin email -->
	<div class="field clearfix">
		<label for="infosEmail" class="aligned"><?php echo $this->l('E-mail address:') ?> </label>
		<span class="contentinput">
			<input type="text" class="text required" id="infosEmail" name="admin_email" value="<?php echo htmlspecialchars($this->session->admin_email) ?>" />
			<sup class="required">*</sup>
		</span>
		<?php echo $this->displayError('admin_email') ?>
	</div>

	<!-- Admin password -->
	<div class="field clearfix">
		<label for="infosPassword" class="aligned"><?php echo $this->l('Shop password:') ?> </label>
		<span class="contentinput">
			<input autocomplete="off" type="password" class="text required" id="infosPassword" name="admin_password" />
			<sup class="required">*</sup>
		</span>
		<?php echo $this->displayError('admin_password') ?>
	</div>

	<!-- Admin password confirm -->
	<div class="field clearfix">
		<label class="aligned" for="infosPasswordRepeat"><?php echo $this->l('Re-type to confirm:') ?> </label>
		<span class="contentinput">
			<input type="password" autocomplete="off" class="text required" id="infosPasswordRepeat" name="admin_password_confirm" />
			<sup class="required">*</sup>
		</span>
		<?php echo $this->displayError('admin_password_confirm') ?>
	</div>

	<!-- Recieve by email -->
	<div class="field clearfix" id="contentInfosNotification">
		<span class="contentinput">
			<input type="checkbox" name="send_informations" id="infosNotification" class="aligned" style="vertical-align: middle;" <?php if ($this->session->send_informations): ?>checked="checked"<?php endif; ?> />
			<label for="infosNotification"><?php echo $this->l('Receive this information by e-mail') ?></label>
			<br/>
			<span id="resultInfosNotification" class="result aligned"></span>
		</span>
		<p class="userInfos aligned"><?php echo $this->l('Warning: You will recieve these informations only if your e-mail configuration is correct.') ?></p>
	</div>
</div>

<!-- Partners form -->
<div id="benefitsBlock" style="display: none;"></div>

<?php $this->displayTemplate('footer') ?>