module.exports = {
  Localization: {
    Localization: {
      pack_select: '#select2-import_localization_pack_iso_localization_pack-container',
      pack_search_input: ' html input.select2-search__field ',
      pack_option: '#select2-import_localization_pack_iso_localization_pack-results li[contains(text(),"%B")]',
      import_button: '#main-div form[name="import_localization_pack button',
      advanced_language_identifier_input: '#form_advanced_language_identifier ',
      advanced_country_identifier_input: '#form_advanced_country_identifier ',
      advanced_save_button: '#main-div div.card:nth-child(4) button',
      alert_panel: '#main-div div.%B',
      success_alert_panel: '#main-div div.%B and [role="alert"] div.alert-text ',
      configuration_selected_option: '#%ID option[selected="selected"] ',
      download_pack_data_toggle_button: '#main-div form[name="import_localization_pack span.ps-switch"] label',
      content_import_checkbox: '#import_localization_pack_content_to_import_%B ',
      local_unit_input: '#form_local_units_%D_unit ',
      save_local_units_button: '#main-div button[text()="Save"]:nth-child(2)',
      default_language_list: '#form_configuration_default_language',
      default_country_list: '#form_configuration_default_country',
      default_currency_list: '#form_configuration_default_currency',
      time_zone_list: '#form_configuration_timezone',
      symfony_toolbar: ' *[contains (id, "sfToolbarMainContent")] a',
      save_configuration_btn: '#main-div button:nth-child(2)',
      language_browser_no_label: ' label[for="form_configuration_detect_language_from_browser_0"]',
      country_browser_no_label: ' label[for="form_configuration_detect_country_from_browser_0"]',
      language_browser_yes_label: ' label[for="form_configuration_detect_language_from_browser_1"]',
      country_browser_yes_label: ' label[for="form_configuration_detect_country_from_browser_1"]',
    },
    languages: {
      add_new_language_button: '#page-header-desc-lang-new_language ',
      name_input: '#name ',
      iso_code_input: '#iso_code ',
      language_code_input: '#language_code ',
      date_format_input: '#date_format_lite ',
      date_format_full_input: '#date_format_full ',
      flag_file: '#flag ',
      no_picture_file: '#no_picture ',
      is_rtl_button: '#fieldset_0 label[for="is_rtl_%S"]',
      status_button: '#fieldset_0 label[for="active_%S"]',
      save_button: '#lang_form_submit_btn ',
      success_alert: '#main-div div.alert-text p',
      filter_name_input: '#table-lang input[name="langFilter_name"] | #language_name ',
      filter_search_button: '#submitFilterButtonlang | #language_grid_table button[contains(name,"search")]',
      edit_button: '#table-lang tbody a [title="Edit"]',
      dropdown_button: '#table-lang tbody button[data-toggle="dropdown | #language_grid_table a [data-toggle="dropdown"]',
      delete_button: '#table-lang tbody a [title="Delete | #language_grid_table a [contains(data-confirm-message,"Delete")]',
      reset_button: '#table-lang button[contains(name, "Reset")] | #language_grid_table button[contains(name,"reset")]',
      language_column: '#table-lang td:nth-child(%ID) | #language_grid_table td:nth-child(%ID) a',

    },
    Currencies: {
      new_currency_button: '#page-header-desc-currency-new_currency , #page-header-desc-configuration-add',
      currency_select: '#iso_code , #currency_iso_code',
      exchange_rate_input: '#conversion_rate , #currency_exchange_rate',
      save_button: '#currency_form_submit_btn , #main-div div.card-footer button',
      success_danger_panel: '#main-div div[class*="%B"][role="alert"]',
      search_iso_code_input: '#currency_iso_code',
      search_button: '#submitFilterButtoncurrency , #currency_grid_table button',
      reset_button: '#table-currency button[name=submitResetcurrency] , #currency_grid_table button[type=reset]',
      currency_number_span: '#currency_grid_panel h3',
      currency_iso_code_column: '#currency_grid_table tbody > tr:nth-of-type(%ID) > td:nth-of-type(3)',
      sort_icon: '#currency_grid_table div[data-sort-col-name="%B"] span[role="button"]',
      currency_exchange_rate: '#currency_grid_table tbody tr:nth-child(%ID) td:nth-child(4)',
      enabled_select: '#currency_active ',
      search_no_results: '#table-currency td.list-empty | #currency_grid_table td[colspan=6]',
      check_icon: '#currency_grid_table tr:nth-of-type(%ID) > td:nth-of-type(5) i[class*=%ICON]',
      status_currency_toggle_button: '#currencyStatus , label[for=currency_active_%ID]',
      edit_button: '#currency_grid_table td:nth-child(6) a [contains(href, "edit")]',
      cancel_button: '#currency_form_cancel_btn | #main-div form[name="currency a',
      table_currencies: '#table-currency | #currency_grid_table ',
      action_button: '#currency_grid_table a [class*=dropdown-toggle]',
      delete_action_button: '#currency_grid_table a [data-confirm-message*="Delete selected"]',
      live_exchange_rate_toggle_button: ' label[for="form_exchange_rates_live_exchange_rate_%ID"]',
      update_exchange_rate_button: '#main-div form[name="exchange_rates button'
    },
    Geolocation: {
      download_file_link: '#main-div a [contains(text(),"this file")]',
      ip_address_yes_label: ' label[for="form_geolocation_by_id_address_geolocation_enabled_1"]',
      ip_address_no_label: ' label[for="form_geolocation_by_id_address_geolocation_enabled_0"]',
      save_geolocation_ip_address_button: '#main-div button[contains(text(),"Save")]:nth-child(1)',
      alert_panel: '#main-div div.%B [role="alert"] div.alert-text ',
    }
  }
};
