module.exports = {
  Location: {
    State: {
      country_select: '#table-state select[name="stateFilter_cl!id_country"]',
      search_button: '#submitFilterButtonstate',
      state_field_column: '#table-state tr:nth-child(%L) td:nth-child(%C)',
      search_country_option_list: '#table-state select[name="stateFilter_cl!id_country"] option[text()="%B"]'
    },
    Zone: {
      add_new_zone_button: '#page-header-desc-zone-new_zone',
      cancel_button: '#zone_form_cancel_btn',
      zones_table: '#table-zone',
      name_input: '#name',
      save_button: '#zone_form_submit_btn',
      reset_button: '#table-zone button[name="submitResetzone"]',
      alert_panel: '#content div.bootstrap div.%I',
      search_zone_input: '#table-zone input[name="zoneFilter_name"]',
      search_id_input: '#table-zone input[name="zoneFilter_id_zone"]',
      search_button: '#submitFilterButtonzone',
      enabled_disabled_icon: '#table-zone tr:nth-child(%ID) td:nth-child(4) a i.%ICON',
      sort_icon: '#table-zone span[contains(text(),"%B")] a:nth-child(%W)',
      number_zone_span: '#form-zone span.badge',
      element_zone_table: '#table-zone tbody tr:nth-child(%ID) td:nth-child(%B)',
      search_enabled_list: '#table-zone select[name="zoneFilter_active"]',
      edit_delete_button: '#table-zone td:nth-child(5) a [title="%B"]',
      dropdown_button: '#table-zone td:nth-child(5) button',
      bulk_action_button: '#bulk_action_menu_zone',
      action_group_button: '#form-zone div.bulk-actions a:nth-child(%ID)',
      checkbox_input: '#table-zone > tbody > tr:nth-child(%B) > td.row-selector.text-center > input',
      search_by_zone_checkbox: '#table-zone tbody td[contains(text(),"%B")] td:nth-child(1)',
      search_by_zone_icon: '#table-zone tbody td[contains(text(),"%B")] td:nth-child(4) a i.%ICON'
    },
    Country: {
      search_zone_list: '#table-country select[name="countryFilter_z!id_zone"]',
      reset_button: '#table-country button[name="submitResetcountry"]',
      search_zone_option_list: '#table-country select[name="countryFilter_z!id_zone"] option[text()="Asiaaa"]',
      add_new_country_button: '#page-header-desc-country-new_country',
      country_input: '#name_1',
      iso_code_input: '#iso_code',
      call_prefix_input: '#call_prefix',
      default_currency_select: '#id_currency',
      zone_select: '#id_zone',
      need_zip_code_yes_label: ' label[for="need_zip_code_on"]',
      zip_code_format_input: '#zip_code_format',
      clear_format_button: '#eraseCurrentLayout',
      address_format_field_textarea: '#ordered_fields',
      address_format_tab: '#custom-address-fields a [contains(text(),"%B")]',
      customer_birthday_button: '#Customer:birthday',
      customer_lastname_button: '#Customer:lastname',
      customer_firstname_button: '#Customer:firstname',
      address_last_name_button: '#lastname',
      address_first_name_button: '#firstname',
      address_address1_button: '#address1',
      address_address2_button: '#address2',
      address_dni_button: '#dni',
      address_postcode_button: '#postcode',
      address_city_button: '#city',
      address_phone_button: '#phone',
      country_name_button: '#Country:name',
      save_button: '#country_form_submit_btn',
      alert_panel: '#content div.bootstrap div.%B',
      search_iso_code_input: '#table-country input[name="countryFilter_iso_code"]',
      search_country_input: '#table-country input[name="countryFilter_b!name"]',
      search_id_input: '#table-country input[name="countryFilter_id_country"]',
      search_button: '#submitFilterButtoncountry',
      number_country_span: '#form-country span.badge',
      element_country_table: '#table-country tr:nth-child(%ID) td:nth-child(%B)',
      enabled_disabled_icon: '#table-country tr:nth-child(%ID) td:nth-child(7) a i.%ICON',
      search_enabled_list: '#table-country select[name="countryFilter_a!active"]',
      sort_icon: '#table-country span[contains(text(),"%B")] a:nth-child(%W)',
      pagination_button: '#form-country div.pagination button',
      pagination_element: '#form-country div.pagination li a [contains(text(),"%NUMBER")]',
      edit_button: '#table-country tbody tr:nth-child(1) td:nth-child(8) a',
      use_default_format_button: '#useDefaultLayoutSystem',
      use_last_registered_format_button: '#useLastDefaultLayout',
      contain_states_yes_button: ' label[for="contains_states_on',
      restrict_country_selections_button: '#conf_id_PS_RESTRICT_DELIVERED_COUNTRIES label[for="PS_RESTRICT_DELIVERED_COUNTRIES_%B"]',
      country_option_save_button: '#country_fieldset_general button',
      bulk_action_button: '#form-country button.dropdown-toggle',
      action_group_button: '#form-country div.bulk-actions a:nth-child(%ID)'
    }
  }
};
